### ISSUE TITLE
Exceptions and error handling model inside the library

### ISSUE THREAD

**Issue by intelfx** [CNugteren/CLBlast#110]
I've noticed that the exception model inside the library is pretty strange. The OpenCL wrapper throws exceptions which are caught halfway by nested catch statements repeated inside each routine and converted to error codes.

At the same time, the exception thrown from `database.cpp` is not caught in any way (and I vaguely remember other exceptions leaking into the client, too).

Will you accept a patchset converting the library to use custom exception objects carrying their own own error codes, and then catching all exceptions at the topmost level only?

**Comment by CNugteren** [comment]
Perhaps that is a good idea indeed. The library was not really designed properly in terms of exception handling I guess. Perhaps this is also partly due to the fact that it should return error codes in the end and not throw exceptions. Or could we have both: error codes for expected errors (e.g. wrong input argument values) and exceptions for internal errors / bugs in the library (e.g. database errors)?

Also the reason that the OpenCL wrapper is different is that it is also used in an external project (CLCudaAPI).

But if you have a good plan and good arguments I will accept changes to the exception model.

**Comment by blueberry** [comment]
Please also note that CLBlast is used in external libraries on JVM (JOCLBlast and Neanderthal), so do not break the existing way we can catch those errors :)

**Comment by intelfx** [comment]
@blueberry Which errors do you handle and how exactly do you want to be able to handle them?

Current model of error handling in CLBlast is really inconsistent, e. g. any (both OpenCL, internal CLBlast and C++ runtime) errors thrown in "setup" phase are not handled at all, but any errors thrown in "run" phase (inside of the Routine subclasses) are wildcard caught, erased of actual exception type(!) and returned as generic error codes coarsely corresponding to the high-level action that caused an error.

**Comment by blueberry** [comment]
Probably the easiest and most consistent way for managd environments such as JVM is "the C way", just like in plain OpenCL. You call the method, and it returns the error code that you handle as you please in that environment. Of course, I don't mind if there is something else for C++, but that would probably be a bit more difficult to handle from java. I think @gpu is the right person to ask about those things, since he created the JVM CLBlast wrapper.

**Comment by CNugteren** [comment]
@intelfx You are right that it is a mess. I propose the following changes:

1. All exceptions thrown internally in CLBlast should be caught and a proper error code should be returned instead. If an appropriate error code does not exist yet it should be added. For JOCLBlast this would mean just adding some error codes to the enum.

2. All errors caught by the OpenCL header (`clpp11.h` / CLCudaAPI) should be handled in custom exceptions (instead of the generic exception right now) such that the source of the error becomes clear. CLBlast should catch these and according to point 1 above an appropriate error should be returned.

Do you agree with these changes? If so, I can also make the changes if you want, perhaps easier since I know the codebase.

**Comment by intelfx** [comment]
@blueberry @CNugteren 

My plan was roughly following. **Regarding the API:**

* for C++ API:
  - use error codes for semantic BLAS errors
  - use exceptions for C++ runtime errors (i. e. don't catch `std::bad_alloc`)
  - use either error codes or custom exceptions for OpenCL and internal CLBlast errors (see below)

* for C API:
  - catch all exceptions thrown by C++ API and convert them to error codes

**Regarding the "see below" above:** if we decide to return error codes for OpenCL errors, we probably should have a 1-to-1 mapping from OpenCL errors to `clblast::StatusCode`, rather than shove all of them into one (or a few) status code(s).

**Regarding the implementation:**

1. Get rid of all status codes *inside* CLBlast. Use only exceptions, with the "exception dispatcher" pattern at the topmost level;

2. Implement a hierarchy of internal exception classes roughly corresponding to high-level logical actions, or, ideally, a type per error kind (this would be useful anyway, if/when we decide to use exceptions in the API).

**Comment by CNugteren** [comment]
OK, I agree with your reasoning. In CLBlast there are already a lot of statuscodes that have a 1-to-1 mapping to OpenCL error codes, I think we should extend them. So, in summary (copying from above):

* for C++ API:
  - use error codes for semantic BLAS errors: starting at -1024 sharing error code values with clBLAS.
  - use error codes for internal CLBlast errors: starting at -2048.
  - use error codes for OpenCL errors: around 0 and going lower.
  - use exceptions for C++ runtime errors (i. e. don't catch `std::bad_alloc`)

* for C API:
  - catch all exceptions thrown by C++ API and convert them to error codes

For the implementation it makes sense indeed to use exceptions internally and then catch them all at the lowest level. Do we need a hierarchy of exception class or just 3 classes for the above types?

Will you be implementing this? If so, be aware that some larger repetitive files (like `clblast.cpp`) are generated by a Python script included in the `scripts/generator` subfolder.

**Comment by intelfx** [comment]
I'd rather make an exception type for each error kind and then organise them in a hierarchy where each error category is a base class (just like in C++ standard library).

Given that `clblast.cpp` is generated, we could even make an exception-based version of the API in a different namespace.

And yes, I already have a WIP branch on exceptions, I'll just have to finish it according to the discussion :)

**Comment by CNugteren** [comment]
OK, sounds great! Let me know if you need any input or help.

**Comment by gpu** [comment]
blueberry notified me above. My thoughts, starting with a disclaimer:

I'm not sure what a C++ programmer might expect or wish for when using a BLAS library. One could argue that exceptions are the "modern" way of communicating errors, even in C++. But BLAS goes back to some Fortran interface, and people might *expect* a certain interface here - and error codes seem to be the most common one.

Additionally, I'm not familiar with som best practices in C++. One could assume that something like a `std::bad_alloc` is *so* low-level that it should hardly ever be caught (and I think that in most cases, it will not be handled at all), but graciously returning, for example, a `CL_OUT_OF_HOST_MEMORY` or a more specific status code may be reasonable here.

---

However, intuitively, differentiating between the classes of errors (C++/OpenCL/BLAS, as sketched above) certainly makes sense. And the proposed implementation of a hierarchy, e.g. creating a `clblast::blasException` that can be caught separately from a  `std::exception` sounds like a reasonable approach for me.

Regarding the Java wrapper. The actual interface for the wrapper is the C interface, and this is offered 1:1, so there is no exception handling at all. 

(One could consider catching things like `std::bad_alloc` in the wrapper, and convert it into a Java `OutOfMemoryError`, but this is uncommon, at least.)

(BTW: On Java side, there is a flag to enable exceptions, which boils down to going the opposite direction of what was proposed now: *If* a function of the C interface returns an error code, then a new Java exception is thown).

**Comment by intelfx** [comment]
@gpu

Thanks for your comments. So, we've actually already agreed to catch everything (incl. C++ runtime errors) inside the C API, so you're safe.

Anyway, we've settled on reporting everything except C++ errors as return codes as well. For the `std::bad_alloc` — the buffer allocations are happening via CL API calls, so they will be returned as CL errors. The `std::bad_alloc` will happen e. g. if there is no memory for a shared pointer or suchlike.

**Comment by intelfx** [comment]
@CNugteren are you OK with having an **optional** dependency on Boost.Compute to convert OpenCL error codes to strings?

**Comment by CNugteren** [comment]
Thanks for the discussion and feedback!

About the Boost dependency, is that really necessary? When would you need the strings? We convert to error codes anyway in the end, right?

**Comment by intelfx** [comment]
@CNugteren well, for `what()` in exception-ed version of the API, and for `clblast::strerror()`. No, it's not necessary at all — pure convenience.

**Comment by CNugteren** [comment]
This is now resolved through PR #117.
