### ISSUE TITLE
Unable to test/tune for CPU device in OS X (error code -54)

### ISSUE THREAD

**Issue by mrTsjolder** [CNugteren/CLBlast#139]
I tried to install CLBlast on my 2011 macbook pro to come to the conclusion that most of the tests just skipped, stating `CLBlast: OpenCL error: clEnqueueNDRangeKernel: -54` which turns out to be a `CL_INVALID_WORK_GROUP_SIZE` (as I found out [here](https://streamcomputing.eu/blog/2013-04-28/opencl-error-codes/)).

After some googling I [discovered](http://stackoverflow.com/questions/10065681/opencl-kernel-work-group-size-restriction) that the OpenCL implementation from Apple would only support a single worker for a CPU. I thought to be able to circumvent this issue by tuning, but that only lead to segmentation faults or just empty results (because parameters for the number of workers starts at 8).

**Comment by CNugteren** [comment]
Yes, Apple's CPU OpenCL implementation is a strange one. You are completely right with your conclusions: CLBlast doesn't run out-of-the-box and running the tuners will also not help.

I thought many times about building a special case for CPUs using Apple's OpenCL implementation, but I never actually did it. Perhaps this is a good moment to put it on the agenda :-) And if not, there should be a clear warning message plus some documentation.

**Comment by mrTsjolder** [comment]
In an attempt to find an easy solution I tried adding `1` to the parameter search of the tuner, but it turns out that the kernel does not work this way (I got these `[warning] Results differ`). Is this an algorithmic limitation?

I am asking because I thought `device. MaxWorkItemSizes()` could be used for default values, but I am not sure in how far that would be possible/fits in the plan...

**Comment by CNugteren** [comment]
Where exactly are you adding the `1` parameter?

Yes, including something like `MaxWorkItemSizes` could be a good idea. However, that would make tuning runs created with Apple OpenCL not so useful for other platforms with the same Intel CPU. That's why I want to make a special case (i.e if-statement in the code) when running with Apple OpenCL. And perhaps not even tune it... Not sure if there are better alternatives.

**Comment by mrTsjolder** [comment]
In `CLBlast/src/tuning/kernels/copy_fast.cpp`, I changed lines 62-63 (current state in master) as follows: 

    tuner.AddParameter(id, "COPY_DIMX", {1, 2, 4, 8, 16, 32});
    tuner.AddParameter(id, "COPY_DIMY", {1, 2, 4, 8, 16, 32});

This gave those warnings for all possible combinations for which `DIMY = 1`

I thought it might be useful to use device dependent values for the default cases for as far it is possible. In case of the `copy_fast` kernel, `COPY_DIMX` and `COPY_DIMY` could be set to `MaxWorkItemSizes[0]` and `MaxWorkItemSizes[1]` as default values, rather than some static values. The argument therefore could be that this allows to use the maximum (theoretical) potential of the hardware.

I do not really have experience with either C++ or OpenCL, but I already spent quite some time reading through the code to figure out whether following ideas might work:

1.  If in `CLBlast/src/database/database.cpp`, the `Database::Search` method would be passed an OpenCL-device, it would be possible to do something like

        if (device.name == this_device.Name()) {
          // Sets the parameters accordingly
          return &device.parameters;
        } else {
          // Default parameters
          auto parameters = &device.parameters;
          parameters["DIMX"] = device.MaxWorkItemSizes()[0];
          parameters["DIMY"] = device.MaxWorkItemSizes()[1];
          return parameters;
        }

    From a design point-of-view, it would probably be nicer to keep only the device name in the interface, but I am not sure what the best way to find default parameters depending on a device would be...

2. In `CLBlast/src/tuning/tuning.hpp`, the device is available (in `device`) and could be passed to `C::SetParameters(tuner, id);`, such that each routine can set up a set of parameters that are definitely valid.

I am not sure whether these are good/valid ideas, but they seem like "easy" fixes to make sure each device can be configured in such a way that at least, it is possible to run the code. However, the warning seems to indicate that the kernels do not work correctly when one of the dimensions is 1.

**Comment by CNugteren** [comment]
I appreciate your efforts to help out, but as I said it's probably better to treat this as a special case. Treating it as normal tuning results would mess up the tuning database, because the hardware (and thus the OpenCL device name) is the same regardless of the use of Apple's funny OpenCL implementation. Simple example: tuning results on your Macbook under Windows would look completely different. Also the computed averages would make less sense.

Since Apple's OpenCL CPU implementation is a bit crippled, I will make special fall-back case in the code (not part of the tuning results). Other libraries might not even decide to support it at all, e.g. [clFFT](https://github.com/clMathLibraries/clFFT/issues/84), so I guess the number of OpenCL users on CPUs on OS X is limited.

About your changes to the tuning code: probably you didn't change the default case, which is used as a reference. So when it says that the results are different, that probably means that the reference kernel didn't run at all. So you'll have to modify those settings as well.

**Comment by mrTsjolder** [comment]
As I said, I do not have much experience in C++ or OpenCL (yet). I just thought that `MaxWorkItemSizes` would depend on the implementation and therefore might be useful to find valid parameters...

If you need any more information, test runs or whatsoever, I'm at your service ;)

**Comment by CNugteren** [comment]
FYI: I've now 'fixed' Apple CPU support through PR #145 . It doesn't focus on performance, but does make most of the routines work properly. It uses a special-case override database, since Apple's CPU implementation is just a bit of an odd one.
