### ISSUE TITLE
iXamin routine missing 

### ISSUE THREAD

**Issue by blueberry** [CNugteren/CLBlast#151]
iXamin might not be a part of standard BLAS, but both MKL and cuBLAS have it, while CLBlast have iXmin and iXmax non-standard routines. I guess it would be both useful and not difficult to add iXamin to CLBlast?

**Comment by CNugteren** [comment]
Yes, that should be easy to add. It somehow didn't get added in issue #45. I'll let you know when it's available.

**Comment by CNugteren** [comment]
I've implemented the IXAMIN routine. It is available in the latest version of the `master` branch.

**Comment by blueberry** [comment]
Thank you, Cedric. I don't have a C project stup to test it reliably, but I assume that it works well since it is a minor change compared to the existing iamax. I will integrate it into neanderthal and test it as soon @gpu integrates it into JOCLBlast. Is there a possibility of a 0.11.1 of CLBlast soon?

**Comment by CNugteren** [comment]
Ok, understood. Well I tested it myself of course, so should hopefully be fine.

I'm actually planning a 1.0 release soon after I resolve some open issues and known bugs. Would a couple weeks work for you?

**Comment by blueberry** [comment]
@CNugteren Of course! I'm not in a hurry. @gpu prepared JOCLBlast release a few days ago that has not yet been released, so I've thought that maybe it's not too late to jump to 0.11.1 right away. I do not need iXamin specifically right away, it was more a completeness thing. So, especially since 1.0 is around the corner, I don't mind waiting for it.

Thank you for this amazing library.

BTW, since I've just integrated cuBLAS into neanderthal, I've measured a few matrix multiplications just to get a broad sense of the performance. 8192x8192 matrices multiply in 141ms with cuBLAS vs 220 ms with CLBlast on GTX 1080. It looks like a pretty good result for CLBlast to me, not that much slower than very tightly optimized nvidia's lib!

**Comment by CNugteren** [comment]
OK, then I'll close this issue since the routine is implemented. If you encounter any problems later on you can always open an issue and report the specific (performance) problem.

About performance versus cuBLAS: yes, sometimes it is quite decent given the fact that cuBLAS can be optimised at PTX or assembly level and uses certain instructions which we can't access easily from OpenCL C (e.g. `__ldg`). But it's not always that close, see for example benchmark results for [GTX750Ti](https://cnugteren.github.io/clblast/results/GTX750Ti/cublas/sgemm_plot.png) and for [Titan X](https://cnugteren.github.io/clblast/results/TitanXPascal/cublas/sgemm_plot.png).
