### ISSUE TITLE
Database building

### ISSUE THREAD

**Issue by fvella** [CNugteren/CLBlast#165]
Hi,
we noticed that the building of the database takes a lot of time especially for ARM board. The problem is due to the compilation of all the entries in the database for each architecture. 
Do you have some define/mechanism  to skip the building phase of the entries for no-used architectures?

**Comment by CNugteren** [comment]
Indeed, compiling `database.cpp` takes excessively long. Compiling that particular file with -O1 already solves it I believe. It shouldn't need to take long anyway. And it is not a performance critical part, so I'm happy with reorganising the code.

I had this issue on my list but I will give it higher priority.

**Comment by CNugteren** [comment]
I have just started the `database_compilation_speed`, to which I have committed a version of the database which compiles in ~20s instead of ~90s on my machine. Hopefully that will translate to faster compilation times with other compilers as well. I basically removed the redundant parameter names in each entry and save only a per-kernel list of parameter names and for each entry just the values. Perhaps a little less readable now, but compilation time was really long before.

Still need to make some other changes to get everything to work, but you can expect this to be merged into master soon.

**Comment by CNugteren** [comment]
I just pushed some fixes to that branch, it should compile and execute correctly now. Could you test if it is faster on your system as well?

**Comment by fvella** [comment]
Sure, I'll test know.

**Comment by fvella** [comment]
I have the following error:
'''/home/flavio/CK_TOOLS/lib-clblast-tune-master-gcc-6.2.0-linux-32/src/src/database/kernel_selection.hpp:66:1: error: could not convert '{{clblast::database::kDeviceTypeGPU, "Intel", {{"default", {((1 * 1) * 1)}}}}, {clblast::database::kDeviceTypeGPU, "NVIDIA", {{"default", {((1280 * 1280) * 1280)}}}}, {clblast::database::kDeviceTypeGPU, "ARM", {{"default", {{"XGEMM_MIN_INDIRECT_SIZE", ((128 * 128) * 128)}}}}}, {clblast::database::kDeviceTypeAll, "default", {{"default", {((512 * 512) * 512)}}}}}' from '<brace-enclosed initializer list>' to 'std::vector<clblast::Database::DatabaseVendor>'
'''

**Comment by fvella** [comment]
I cleaned the environment and now it works.

**Comment by CNugteren** [comment]
OK, thanks for testing! But is it faster on your system now? And is it fast enough to consider the issue solved?

**Comment by fvella** [comment]
Yes, it is fast enough. Thanks
