### ISSUE TITLE
Fixed unrolling factor in Xgemv kernel?

### ISSUE THREAD

**Issue by RichardSchulze** [CNugteren/CLBlast#183]
I saw that CLBlast uses an unrolling factor in Xgemv. The kernel code says
```
#ifndef UNROLL1
  #define UNROLL1 32  // Unroll factor (must be a divider of WGS1)
#endif
```
I could not find any host code that sets the `UNROLL1` parameter or a tuner that determines this value. Is it correct that `32` is always used? Why is this parameter not tuned when tuning Xgemv?
Thanks in advance!

**Comment by CNugteren** [comment]
I think you are right indeed. Yes, 32 seems to be always used. Not sure why I didn't add it as a tuning parameter, probably because some experiments showed that it didn't matter too much and it would only increase the size of the tuning space. You can still set it manually yourself of course.

How did you came across this issue? Did you find better/worse performance with other unroll factors? Note that not all compilers actually respect `pragma unroll`.

**Comment by RichardSchulze** [comment]
Thanks for your answer. I am evaluating CLBlast and came across these lines when taking a closer look at the Xgemv kernel.
