### ISSUE TITLE
clblast.dll accessviolation error on exit

### ISSUE THREAD

**Issue by sat8** [CNugteren/CLBlast#199]
Hi

Many thanks for this excellent library. I am using CLBlast in my project https://github.com/sat8/YoloOCLInference to enable a state of the art object detection algorithm (based on deep learning) to run on opencl enabled hardware. The benchmarks suggest that the opencl port produces better detection speeds compared to CUDA variant. In addition to my own optimizations, I consider CLBlast contributing positively to the detection speeds.

Everything works fine but upon graceful termination of the app, an access violation pops up as below.

![image](https://user-images.githubusercontent.com/8937796/31427324-c5065c50-ae5e-11e7-8d0b-9690987ac344.png)

The stack trace doesnot tell me much apart from suggesting that it is originating from clblast.dll.

![image](https://user-images.githubusercontent.com/8937796/31427295-b20745b0-ae5e-11e7-84af-13f68e3ad3d6.png)

The debug built dll gives a bit more info suggesting that the access violation is originating from clpp11.hpp file

![image](https://user-images.githubusercontent.com/8937796/31427664-f0956a2c-ae5f-11e7-9195-9eb06daf9645.png)

and the call stack in this case is below

![image](https://user-images.githubusercontent.com/8937796/31427700-10dffc8e-ae60-11e7-841d-ec380f74b849.png)

Can you put me on the right track to debug this? thnx

SetUp:

-NVIDIA GTX 1080Ti
-(3 OpencL sdk's installed - NVIDIA, AMD, Intel)
- I am not passing a cl_event for clblast::Gemm() call (doing so improves processing speeds). Is this a violation of how CLBlast should be used? Having said that passing cl_event didnot make a difference.
- The issue happens even with an AMD card (RX 580)

**Comment by CNugteren** [comment]
I'll take a look soon at this issue.

In the meantime, can you confirm that the included CLBlast tests run fine? And do you also experience this issue when you run one of the included CLBlast clients?

**Comment by sat8** [comment]
thnx.

I just tried one client app from CLBlast, clblast_client_xgemm.exe and the app demonstrates a similar behaviour to what I reported with my app.

![image](https://user-images.githubusercontent.com/8937796/31453954-c528c496-aeab-11e7-9451-fa3e99d5e2b2.png)

and the call stack output is as below

![image](https://user-images.githubusercontent.com/8937796/31453982-d7e9d5f2-aeab-11e7-9745-b5e7bb1271cb.png)

I have had all 3 OpenCL SDKs  (Intel, NVIDIA, AMD) installed when my app had an issue on termination. Before running the client app, clblast_client_xgemm.exe I have uninstalled Intel & AMD APP sdks thus leaving NVIDIA. I verified that CMake and MSVC projects were pointing to NVIDIA CUDA SDK before CLBlast and client apps were built and run. Let me know if you need me to check anything else at my end.

**Comment by CNugteren** [comment]
I'll have to test this myself under Windows, I can do that in a couple of days. One thing you could try is just to comment out that line, because it seems it is only crashing at clean-up of the OpenCL program. So the only drawback of not doing that would be memory-leaks. Can you try if that does 'solve' it?

**Comment by sat8** [comment]
many thnx @CNugteren .

I can certainly try the interim solution you have suggested but would limit it to myself.  (Although, I would prefer others to get CLBlast from here and link against my project so that they get all the bug fixes in CLBlast). 

Meanwhile, I can validate the same issue on Ubuntu 16.04 and update the status here.

**Comment by CNugteren** [comment]
Yes, of course I agree that this should be solved properly.

By the way, when you run the included CLBlast tests, do you also see this behaviour? I'm asking this because there are [automated tests on 3 different Windows systems](http://ci.arrayfire.org/view/Other/) which don't show any issues. However, they only run the tests, not the clients.

**Comment by sat8** [comment]
thnx.

I am afraid, I do see the same behaviour when running the included tests. For instance this is a screen grab for clblast_test_xamax.exe when running in debug mode.

![image](https://user-images.githubusercontent.com/8937796/31573815-dea1914e-b0ba-11e7-8236-0bd113e68dd7.png)

**Comment by CNugteren** [comment]
OK, in that case it is thus not an issue on all Windows systems. At least on the 3 Jenkins systems it works fine, whereas on your machine it doesn't. However, you told me that you tried with different OpenCL's of different vendors, so that also doesn't seem the issue. So I would try to find out what's different on your system compared to on the Jenkins test systems. For example, which compiler do you use? And are you on the latest version of CLBlast?

You can find output of builds and tests for the 3 test systems here:
* http://ci.arrayfire.org/view/Other/job/other/job/CLBlast-Windows-Intel/141/consoleFull
* http://ci.arrayfire.org/view/Other/job/other/job/CLBlast-Windows-NVIDIA/99/consoleFull
* http://ci.arrayfire.org/view/Other/job/other/job/CLBlast-Windows-AMD/89/consoleFull
These 3 tests include using Visual Studio 2013 and 2015.

One other thing you could try is run the included samples in CLBlast (-DSAMPLES=ON). They are even simpler programs compared to the clients and tests. Do the issues also occur there? And do they show up for every sample program?

**Comment by sat8** [comment]
Ok, it makes sense that my system is not inline to test system shared in your post. However, is there a way I can get the test apps to log the device name on which the concerned tests are running? Does passing -DVERBOSE to cmake help?

I  ask this because, my system has an i7-6770 CPU that has HD graphics 530 GPU built in and a GTX 1080Ti. With two opencl devices onboard, I need to be sure that the tests & samples from CLBLast are running on NVIDIA card or not. Reading about clTune, I understand that environment variables CLBLAST_DEVICE, CLBLAST_PLATFORM can be picked up by test apps. Does this apply to CLBlast too?

**Comment by CNugteren** [comment]
>  I understand that environment variables CLBLAST_DEVICE, CLBLAST_PLATFORM can be picked up by test apps. Does this apply to CLBlast too?

Yes, it does apply, see the README. However, the clients and test programs also have a `-platform X` and `-device Y` command-line option, which is probably more intuitive to use. The test programs also print the device name on which they are running. There is also an included `clblast_test_diagnostics` program which you run to query information about a particular platform or device.

**Comment by sat8** [comment]
@CNugteren, I am closing this for the moment as I need time to tidy up (reinstall os etc.,), verify and then replicate the issue. thnx
