### ISSUE TITLE
Feature request - Clients with override params option

### ISSUE THREAD

**Issue by sivagnanamn** [CNugteren/CLBlast#210]
At present, there's no way to test the performance of Override API without writing code. It would be very useful if custom kernel parameters can be passed to the existing client programs.

Ex:  `./clblast_client_xgemm -MWG 32 -NWG 32 ... `

**Comment by CNugteren** [comment]
Well there is a way: by using the python script (`python ../scripts/database/database.py . ..`) as described in the README. But perhaps it would be nice to do it more direct.

What if I implemented an override argument to all clients which would point to a JSON file as produced by the tuner which would then be loaded and passed to the Override API? All these individual arguments as you propose it can become quite a mess...

**Comment by sivagnanamn** [comment]
I mentioned passing individual parameters as arugments just as an example for better understanding. Adding override argument to clients pointing to JSON file will be the better implementation :+1:

**Comment by CNugteren** [comment]
I've started implementing this, a first version is in the [override_params_from_json branch](https://github.com/CNugteren/CLBlast/commit/8c9ecd97366980200a58a4b8cd77bd7f8b859abc), however I now see it is based on an environmental variable, whereas it is perhaps better to make it a command-line argument (as also discussed here). I'll change that.

One thing to be added is support for multiple JSON files, since e.g. GEMM has multiple kernels. Another thing is that some JSON files are only partial, e.g. the GEMV and DOT kernels need multiple files. That would require some re-structuring it seems.

**Comment by CNugteren** [comment]
I've fixed the earlier mentioned issues. I haven't extensively tested it yet, but perhaps you can have a go as well to see if this is what you intend to have? Here is an example running the AXPY client:

```
clblast_client_xaxpy -tuner_files clblast_xaxpy_32.json,clblast_xdot_1_32.json,clblast_xdot_2_32.json 

* Reading override-parameters from 'clblast_xaxpy_32.json'
* Found parameters for kernel 'Xaxpy': { VW=1 WGS=64 WPT=1 }
* Reading override-parameters from 'skylake_gpu/clblast_xdot_1_32.json'
* Found parameters for kernel 'Xdot': { WGS1=32 }
* Reading override-parameters from 'skylake_gpu/clblast_xdot_2_32.json'
* Found parameters for kernel 'Xdot': { WGS2=64 }
* Applying parameter override successfully for 'Xdot'
* Applying parameter override successfully for 'Xaxpy'
```

As you can see I passed three comma-separated files as argument. One is for AXPY, and the other two are combined to set the parameters for the DOT routine (not relevent for this particular client, but just for illustration).

All of this requires the JSON files to be generated using the newly integrated auto-tuner (latest master), otherwise it won't work.

**Comment by CNugteren** [comment]
This is now tested and merged into master.
