### ISSUE TITLE
Feature request -  Winograd convolution

### ISSUE THREAD

**Issue by sivagnanamn** [CNugteren/CLBlast#213]
Request to support Winograd convolution feature (faster than im2col + GEMM). Currently not many libraries support this except few like NEON  & cuDNN v5.1 or later etc., This feature will be a good value addition to CLBlast. Please consider for future releases.

**Comment by CNugteren** [comment]
I'm not sure if Winograd is always faster compared to im2col and GEMM. Anyway, it would be nice to have it, perhaps within CLBlast, but perhaps it fits better in other libraries such as [GreenTea libDNN](https://github.com/naibaf7/libdnn) or [tiny-dnn](https://github.com/tiny-dnn/tiny-dnn).

Bottom-line is that I will close this issue simply because there are other more-BLAS-like priorities for CLBlast and there is limited time. Perhaps at a later stage this can be reconsidered.

**Comment by TaihuLight** [comment]
@sivagnanamn @CNugteren 
XCONVGEMM has been added into CLBlast v1.5.0, do you reconsider that adding Winograd convolution to CLBlast again?

**Comment by CNugteren** [comment]
XCONVGEMM is currently implemented as im2col + GEMM, so that is still a bit more in the realm of BLAS than Winograd. Also, there is still first work left to integrate the two kernels to reduce memory usage.

**Comment by Ttl** [comment]
If you are looking for Winograd convolution for inference use take a look at F(4x4, 3x3) Winograd convolution in Leela Zero: https://github.com/gcp/leela-zero/blob/next/src/kernels/convolve3.opencl

It requires compiling kernels for the exact image dimensions, pre-transforming filters and tuning the parameters for the problem, but as a result it's very fast and can even beat cudnn in Leela Zero use case (it's faster at batch size 5 than cudnn at batch size 32). It achieves in practice two times the theoretical maximum GFLOps of im2col convolution and should be much faster for most of the image sizes.
