### ISSUE TITLE
Numpy Interface

### ISSUE THREAD

**Issue by fstakem** [CNugteren/CLBlast#223]
Does anyone have experience interfacing CLBlast with Numpy? Is this easily possible or is there any documentation out there on this?

**Comment by CNugteren** [comment]
I guess you could start with [pyopencl](https://pypi.python.org/pypi/pyopencl) to set-up OpenCL in python. Then, using pyopencl, you can also copy your numpy array from the host to the device as OpenCL memory. Then the only thing remaining is bindings for CLBlast in python.

It seems there is already such a thing for clBLAS named [pyclblas](https://github.com/jroose/pyclblas). I guess it should not be too hard to change it for CLBlast, since the interface is almost the same. [Here's an example](https://github.com/jroose/pyclblas/blob/master/examples/clblasSgemm.py) of what the result would look like.

Makes sense to have something like pyclblas directly in the CLBlast repository. I'm a bit busy with other things right now, but I'll put it on the roadmap for later. In the meantime any help is appreciate, as I don't have much C/Python interfacing experience.

**Comment by fstakem** [comment]
I was more thinking about replacing the BLAS numpy runs on with CLBlast. I have switched out numpy from running on openblas to atlas and was wondering if CLBlast could do the same.

**Comment by CNugteren** [comment]
Ah, I see. But that would only be beneficial for certain types of operations depending on your system because of the additional data-transfer. For example, doing a AXPY or a DOT operation would probably be limited by the PCI-Express bus (depending on your system of course). Perhaps only for BLAS level-3 this would be beneficial, but again that depends on the system and on the size of the operations. That's why I think it is better to have regular Python bindings and let the user control when to transfer data from host to device.

What you could do for your use-case is to compile the library with the Netlib interface, see [the README](https://github.com/CNugteren/CLBlast#using-the-library-netlib-api). That way CLBlast acts as a regular CBLAS library with data transfers included. Then you could just use it as if it is OpenBLAS or ATLAS.

**Comment by fstakem** [comment]
I think the most obvious use case is being able to write signal processing or machine learning code on my laptop and then deploy that same code to my server or a production environment. The compute would scale with the hardware and the data scientist code would not have to be rewritten for a production environment. The production environment would be equipped with more parallel processing such as a GPU with the BLAS library handling the differences in hardware.

**Comment by CNugteren** [comment]
Yes, I understand, but unfortunately it is not as easy as that. As I said before, just running BLAS routines one-by-one with data-transfer back and forth at every call might actually deteriorate performance. Even if we would study that use-case in detail and could decide what the best device is to run on, the real benefits are gained when transferring data to and from the GPU only when needed, e.g. in the beginning and end of a program. That would require re-writing your code with e.g. pyopencl, but that's not transparent in the sense that you describe. Automatically inserting data-transfers at the right point is a topic for a PhD, so I'm afraid I can't help you beyond what I already suggested.

**Comment by fstakem** [comment]
...or that would be the scope of a third party vendor or open source project. PYNQ is a start. Without numpy support for the time being everything done by a data scientist will have to rewritten by a software engineer which is a real time sink.

**Comment by CNugteren** [comment]
As discussed above, the original request is not possible within the scope of CLBlast. Nevertheless, it makes sense to create a Python interface to the library. This is now available in the form of PyCLBlast, see the [pypi website](https://pypi.python.org/pypi/pyclblast/1.0.0) and the [PyCLBlast code and README](https://github.com/CNugteren/CLBlast/tree/master/src/pyclblast).
