### ISSUE TITLE
Crashing when using Intel OpenCL drivers and SDK on Ubuntu 16.04

### ISSUE THREAD

**Issue by matemat13** [CNugteren/CLBlast#225]
Hello. When I try to run some of the CLBlast tests, they not only fail, but a very long human-unreadable back trace and memory log is written to the terminal. Example output when running clblast_test_xgemm:
https://pastebin.com/Qn4Q6FRh
I also cannot run software, which depends on CLBlast (I have been trying this: https://github.com/azuredsky/YoloOCLInference, which hangs the whole computer).

When I try to manually compile some .cl files from the Intel-provided examples, they seem to work. clinfo and tools from Intel for checking the drivers and SDK installation seem to work and indicate no error. Any tips?

My processor is:
Intel Core i7-5557U CPU @ 3.10GHz
and I've been trying to run the tests on the integrated graphics card as well, which is:
Intel Iris Graphics 6100
and I am running Ubuntu 16.04 with the 4.7.0 kernel, patched with the Intel OpenCL drivers. uname -a gives me:
Linux printer3d-desktop 4.7.0.intel.r5.0 #1 SMP Tue Dec 5 13:28:40 CET 2017 x86_64 x86_64 x86_64 GNU/Linux

If I can paste any more info to help, I will gladly cooperate. Thank you for any tips on how to resolve this.

**Comment by CNugteren** [comment]
I'm not sure what's going on, but it might look like a bug in the C++ test code rather than in the OpenCL kernels. What compiler have you been using? Perhaps you can run the test in gdb and see if it gives a more detailed report?

Note that you are testing against clBLAS, which was apparently found on your system. Alternatively, you can test against a regular CPU BLAS (e.g. OpenBLAS or ATLAS). Simply install that and then re-run CMake to detect it. Then the tests will have the option to test against a CPU BLAS. This could eliminate a potential bug in clBLAS rather than in CLBlast.

Another thing to try is to see if you see issues when running the CLBlast clients (with and without clBLAS as a reference) or the tuners.

Another option is to test using Beignet instead of the Intel OpenCL drivers. Beignet works on Linux with an Intel GPU and has been tested to work with CLBlast.

**Comment by matemat13** [comment]
Thanks for the fast answer!

Yeah I forgot to mention that I also tried running the tuner and it ended with a similar error, so it's probably not a problem in clBLAS, but I will try installing a CPU alternative and see if that helps. I will also try running it in valgrind/gdb tomorrow and hopefully give more info.

Also thanks for pointing out Beignet, I wasn't aware of its existence. It seems to be compatible with the processor in question as you said, so it might be an alternative if it turns out that the problem is in the official Intel OpenCL SDK.

**Comment by matemat13** [comment]
OK, so results of gcc -v and g++ -g are here: https://pastebin.com/mwndjRjP

When I run ./clblast_test_xgemm in gdb, the output is here: https://pastebin.com/CLzMAdJe
When I run ./clblast_test_xgemm -cblas 0 -clblas 1, the output is basically the same, so it probably isn't an error in cblas.
When I run ./clblast_test_xgemm in valgrind, the output is: https://pastebin.com/8pEMhQ2E

I will try to use the Beignet and see it that helps, because I'm out of ideas on what to do next.

**Comment by CNugteren** [comment]
OK, thanks for the extensive testing! I'll test myself this weekend with Intel OpenCL on Linux. Could you tell me where you downloaded these drivers or which Ubuntu package(s) you installed?

As for some Beignet tests failing, that's only the half-precision tests, right (e.g. HGEMM)? That still happens occasionally, it is a bit tricky to test, so this might not be an actual failure. Anyway, I assume you are not planning to use half-precision, or are you?

**Comment by matemat13** [comment]
I'm sorry, I have the precise links of where I downloaded stuff at the lab, but I will get there on Monday earliest... But I believe I basically used this webpage as the source of the drivers and SDK: https://software.intel.com/en-us/articles/opencl-drivers
That would mean this page to download the drivers:
http://registrationcenter-download.intel.com/akdlm/irc_nas/11396/SRB5.0_linux64.zip
and this page for the SDK:
https://software.intel.com/en-us/intel-opencl

I believe that the software in question makes use of single precision (float). But I have been unable to get it running so far even with Beignet, although that problem is probably not related to CLBlast.

**Comment by CNugteren** [comment]
Thanks for the info! Turns out I actually already had Intel OpenCL installed on my Debian Linux machine. When I run `clinfo` I see two platforms, each with one device. One is the Intel GPU with Beignet, the other is the Intel CPU with Intel OpenCL. Both are tested and work find on my machine:

Since your Intel OpenCL doesn't work with CLBlast, but mine does, I would first suggest to test it with other OpenCL software. For example, you could download AMD's clBLAS and run the included tests.

Also perhaps useful, here is the version and the device I tested with:
```
  Platform Name                                   Intel(R) OpenCL
Number of devices                                 1
  Device Name                                     Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 2.0 (Build 25)
  Driver Version                                  1.2.0.25
  Device OpenCL C Version                         OpenCL C 2.0 
  Device Type                                     CPU
```
Perhaps you can post a similar snippet (obtained from `clinfo`) to compare if we have the same OpenCL drivers?

**Comment by matemat13** [comment]
OK, so my output of clinfo is: https://pastebin.com/5cLvT2zP
Curiously, the Beignet driver recognizes my graphics card correctly to be _'Intel(R) Iris Graphics 6100 BroadWell U-Processor GT3'_ with
`Max work item sizes                             512x512x512`
whereas the official Intel driver sees the card as _'Intel(R) HD Graphics'_ with
`Max work item sizes                             256x256x256`
which I believe is wrong. Maybe the culprit is not in CLBlast after all!

I have tried to run clblast_test_xgemm on all platforms and all devices and the only problematic one is the _'Intel(R) OpenCL'_ platform and _'Intel(R) HD Graphics'_ device, which produces the errors. I'm now looking into testing with some other library as you suggested.

**Comment by CNugteren** [comment]
Any update from your side?

I took a look at your set-up with Intel OpenCL:
```
  Platform Name                                   Experimental OpenCL 2.1 CPU Only Platform
Number of devices                                 1
  Device Name                                     Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 2.1 (Build 10)
  Driver Version                                  1.2.0.10
  Device OpenCL C Version                         OpenCL C 2.0
  Device Type                                     CPU
```
If you compare that to my set-up which I posted above you can see that your driver is older, but your OpenCL platform is newer (experimental OpenCL 2.1). Perhaps you could try to get a newer driver and/or an older (non-experimental) OpenCL platform from Intel?

**Comment by matemat13** [comment]
Sorry, I had to continue working on the project I actually wanted to use this for in the first place. But it seems to be working OK with Beignet. The drivers and platform I used were the newest I could download from Intel website, so I'm not sure how you can have a newer platform... Anyways I'm afraid I won't have much time for testing this anymore as I have to work on my masters thesis right now :(

**Comment by CNugteren** [comment]
OK, good to know Beignet works. And thanks for reporting! Best of luck with the thesis :-)

The platform is indeed newer (too new since it says experimental?), but the driver is older than the one I have. Anyway, for now I'll close this issue. If you or anyone else encounters issues with Intel's OpenCL implementation, feel free to re-open this issue.

**Comment by CNugteren** [comment]
OK, good to know Beignet works. And thanks for reporting! Best of luck with the thesis :-)

The platform is indeed newer (too new since it says experimental?), but the driver is older than the one I have. Anyway, for now I'll close this issue. If you or anyone else encounters issues with Intel's OpenCL implementation, feel free to re-open this issue.
