### ISSUE TITLE
Faster sgemm for intel?

### ISSUE THREAD

**Issue by kodonnell** [CNugteren/CLBlast#257]
Are you aware of the intel-optimized sgemm code [here](https://software.intel.com/en-us/articles/sgemm-ocl-opt)? In my case (i5-5250u), the output is:
```
$ ./gemm
# device name: Intel(R) HD Graphics
# device slm size: 65536
# device max work group size: 256
# Max compute units  (GPU): 48
# Max clock freqency (GPU): 950.000000
# Peak float perf    (GPU): 729.600000
# build options:  -cl-mad-enable -cl-fast-relaxed-math
# matrix size: 512x512x512
# name                                 time(ms) GFLOPS  Efficiency
Unoptimized                           14.306    18.8     2.6 %
L3_SIMD_4x8x8                          0.868   309.4    42.4 %
MediaBlockRW_SIMD_2x32                 0.701   382.9    52.5 %
MediaBlockRead_SIMD_1x16_2_fp16       [invalid]
```

(the last is invalid as this is gen 8 so native half precision isn't supported). Anyway, that's peaking at 380 gflops with their best algorithm - and also untuned. I don't know what the algorithms are, but I did validate them and they were giving the same result as `numpy` on the CPU.

If I tune CLBlast (setting alpha=1 and beta=0 so it's just A*B - or is it?):

```
$ ./clblast_tuner_xgemm -m 512 -n 512 -k 512 -alpha 1 -beta 0 -runs 10
...
* Found best result 1.34 ms: 200.5 GFLOPS
* Best parameters: KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=64 PRECISION=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4
...
```

So that's nearly half the performance. The intel approach is limited (it only works on square matrices, and not for all sizes), though I wouldn't expect it to have such an effect. It's also not full gemm (i.e. no `+ beta * C` matrix) etc.

What are your initial thoughts @CNugteren ?

This purpose of this issue is to see if that's an apples-for-apples comparison, and if it is, provide a reference for optimising gemm further (assuming it doesn't breach Ts&Cs) - though possibly only for intel.

As an aside - you might also find some of the functions in `clDNN` useful: https://github.com/intel/clDNN/tree/master/kernel_selector/core/cl_kernels

**Comment by CNugteren** [comment]
Thanks, that's a helpful link indeed :-)

Yes, it is not easy to write general OpenCL code that's fast on every device, but this is a quite concrete example and I'll investigate when I have more time (next month perhaps?) to try to make CLBlast more generic such that it includes this particular use-case in the tuning search space.

**Comment by kodonnell** [comment]
Great, glad it's useful. I'd be interested to see whether it does only apply to intel, or has some tricks that could apply generally. Another new intel offering is `iclGPU` or `iclBLAS` - though I think they're just naive kernels for now.

Will leave this issue open until you (or someone else) reports back. 

As an aside - have you ever though about making it easier to support multiple kernels for the same function (including community supplied ones)? I.e. currently we only really tune the parameters for one kernel - it'd be nice to also try different kernels. It shouldn't be too hard, given the BLAS API is well defined etc. If this hasn't already been considered, then I'll start this up in a different thread.

**Comment by CNugteren** [comment]
I've just run Intel's code on my test machine (i5-6200U Skylake ULT GPU), and I get:
```
# device name: Intel(R) HD Graphics
# device slm size: 65536
# device max work group size: 256
# Max compute units  (GPU): 24
# Max clock freqency (GPU): 1000.000000
# Peak float perf    (GPU): 384.000000
# build options:  -cl-mad-enable -cl-fast-relaxed-math 
# matrix size: 512x512x512
# name                                 time(ms) GFLOPS  Efficiency
Unoptimized                             16.2    16.5     4.3 %
L3_SIMD_4x8x8                            1.1   236.5    61.6 %
MediaBlockRW_SIMD_2x32                   1.0   262.5    68.4 %
MediaBlockRead_SIMD_1x16_2_fp16          0.5   507.4   132.1 %
```
So that's 260 GFLOPS single-precision, whereas I only managed to get around 140 GFLOPS on this device. So I'll definitely look into their code and see how to incorporate this into CLBlast.

**Comment by CNugteren** [comment]
I've done a test today by putting the Intel `L3_SIMD_4x8x8` kernel into CLBlast and making it work. It works indeed at 230 GFLOPS on my system, even if doing the alpha/beta multiplications. So the actual difference is indeed in this kernel. Looking more closely at the kernel, I observed the use of the [intel_sub_group_shuffle](https://www.khronos.org/registry/OpenCL/extensions/intel/cl_intel_subgroups.txt), which is an Intel specific OpenCL extension. A quick & dirty solution using local memory instead reduced performance of this kernel to ~100 GFLOPS, so that seems to be the real reason why Intel's kernel is so fast.

I could make an Intel-only GEMM kernel, but I don't like having a separate kernel. I'll try to find a way to integrate everything properly with a small if-statement that would enable this extension. But that doesn't seem trivial, as the whole kernel is quite different because of this. I propose I work first on the Qualcomm issue (#228), because some of those kernels also show better performance on Intel GPUs. Once that is properly integrated, I'll take a look at this again to see how easy it is to make work.

**Comment by kodonnell** [comment]
Awesome stuff. FYI, they go through it [here](https://software.intel.com/en-us/articles/sgemm-ocl-opt), including subgroups etc.

Re different kernels - I'm not sure if I've posted this before, but have you considered having multiple kernels for the same method, and the tuner is selecting both the best kernel, and the best params for it? You already do it somewhat with the `xgemm` batched and strided batched etc. - so maybe having a nice API for multiple kernels per method might be good. And, if you don't want to maintain them (or want to encourage people to put cool methods in place, without the additional work of unit tests etc.), you could always create a `contrib` sort of solution, where random kernels (e.g. the intel specific one) can be dumped. Then, as a user, I can optionally include these `contrib` ones, and tune them (so CLBlast would need to support user-created kernels easily).

Re priority - I'm also not sure if this applies to all intel chips with embedded GPUs, or only e.g. later ones. If it only supports some, then maybe not worth it.

**Comment by kodonnell** [comment]
Sorry, [this](https://software.intel.com/en-us/articles/sgemm-for-intel-processor-graphics) article.

**Comment by CNugteren** [comment]
Thanks for sharing that link, I'll look into that when I revisit this issue (btw, you can also edit your messages).

Having multiple kernels is exactly not what I would like to have in CLBlast, I rather work towards one super generic kernel with many options. That way the tuner can nicely explore the tuning space. Because let's say I now start a new kernel, it will share some of the parameters, but not all, it is going to be less flexible and require more maintenance. Two kernels could be possible, but this will quickly grow. The philosophy behind CLBlast is the inverse: one generic tunable kernel. And hopefully that means that this Intel stuff can be fit in as well :-)

That said, it could be nice to have an easy to way to plug-in a custom hard-coded testing, albeit only for testing purposes like this issue.

**Comment by kodonnell** [comment]
Always fun to have different views! I agree with what you're saying, but the way I look at it is taking the generic approach will be hard to do and maintain (as you mentioned, the entire kernel might change trying to use features from specific hardware) - especially as most of the burden will remain with you. If CLBlast was actually a generic *platform* (with some good, generic defaults) for writing BLAS-ish kernels and tuning them (including across multiple kernels), then you could have the community maintaining them, separate from CLBlast itself, etc. - e,g. I could throw in the Intel one. You could even use this as a way to collect kernels specific to certain hardware, which you could then merge into the super-generic kernels later.

Re the difficulty of tuning across kernels - I'm probably missing the point, as it seems pretty easy to me. The kernels could have completely different parameters (or the same parameters named different things), and it doesn't matter: the role of the tuner is to find the fastest tuned kernel, and there's no need to share parameters. Very easy to say "these are my kernels, and these are the parameters to tune for each one". At least, I'm speaking without understanding the current tuning approach - I'd just wrap it up quickly in some python.

However - I'm somewhat off topic now. I'm not an experienced developer, and wouldn't want to send this project the wrong way - just my 2p.

**Comment by kodonnell** [comment]
@CNugteren - have you seen [this](https://01.org/compute-runtime)? New open source drivers from Intel. Might have a play with them.

**Comment by CNugteren** [comment]
As an update for beter performance on Intel GPUs: I have completed the implementation of the Qualcomm GPU kernel, which is now also fully tunable. The PR (#274) will soon be merged in. On my Intel Skylake I already see performance going up from around [~120 GFLOPS](https://cnugteren.github.io/clblast/results/SkylakeULTGT2/sgemm_plot.png) till [~170 GFLOPS](https://github.com/CNugteren/CLBlast/files/1934873/sgemm_plot_tight.pdf).

I believe the new kernel is also suited for the specific `intel_sub_group_shuffle` extension, I'll have a look.

**Comment by kodonnell** [comment]
Results on my i5-5250u (theoretical ~700 GFLOPS), using Intel driver (i.e. not beignet or neo):

```
* Found best result 11.77 ms: 182.5 GFLOPS
* Best parameters: GEMMK=0 KREG=1 KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=64 PRECISION=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=4

...

* Found best result 16.56 ms: 129.6 GFLOPS
* Best parameters: GEMMK=1 KREG=4 KWG=1 KWI=1 MDIMA=4 MDIMC=4 MWG=16 NDIMB=8 NDIMC=8 NWG=64 PRECISION=32 SA=0 SB=0 STRM=0 STRN=0 VWM=2 VWN=4
```

So, unfortunately it's a fair bit slower. I also noticed the second round took a lot longer to compile in some cases - up to 27 seconds.

**Comment by CNugteren** [comment]
Too bad. Well, that's what the tuner is for, selecting the best case out of all cases. On my device at least it is a significant performance boost.

**Comment by CNugteren** [comment]
I managed to have a version with Intel's subgroups working in a similar way as Intel's kernel. It reaches 225 GFLOPS on my system, whereas I get around ~240 GFLOPS with Intel's code. So I think that's good enough, definitely given that we came from ~120 GFLOPS a few weeks ago!

I have sort some last mysteries out and then I'll commit it to a branch so you can also have a go. Perhaps tomorrow or Wednesday evening.

**Comment by kodonnell** [comment]
Awesome stuff - keen to try it!

**Comment by kodonnell** [comment]
OK, I finally got the NEO driver installed, and things have changed:

```
* Found best result 11.92 ms: 180.2 GFLOPS
* Best parameters: GEMMK=0 KREG=1 KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=16 NWG=128 PRECISION=32 SA=1 SB=1 STRM=0 STRN=1 VWM=4 VWN=4
...

* Found best result 12.15 ms: 176.7 GFLOPS
* Best parameters: GEMMK=1 KREG=2 KWG=1 KWI=1 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=64 PRECISION=32 SA=0 SB=0 STRM=0 STRN=0 VWM=2 VWN=2
```

That's surprising, given I was using the Intel driver before this (not beignet), and my understanding is that that's the basis for NEO. Anyway, maybe it was incorrect versions or some such. Or maybe the new driver supports different options, which means it didn't get sent down the new code path (i.e. GEMMK==1 ran the same code as GEMMK==0)?

Either way, if this result is valid, that's a positive.

**Comment by kodonnell** [comment]
Just playing with this myself (to try and learn a bit of OpenCL) - just noticed that in the Intel example, if you uncomment `#define USE_OUT_OF_ORDER_QUEUE`, then you might get a boost - I get 20% increase (for the default 512 matrix size).

**Comment by CNugteren** [comment]
I just pushed to a new `CLBlast-257-intel-subgroups` branch, which has the Intel subgroup shuffling implemented for the new kernel (GEMMK == 1). It is automatically disabled on GPUs that support it, but automatically disabled in case the tuning parameters are not OK for it:: it works only for cases where `NWG/NDIMC` is equal to the subgroup size and `MDIMC` is larger than the subgroup size.

One flaw in the code is that I assume the size to be 8, but I can't seems to easily verify this. First of all it is device + kernel + local workgroup size dependent, and secondly the function to query (`clGetKernelSubGroupInfoKHR`) is OpenCL 2.0 or newer. So let's hope that 8 is a magic constant and doesn't change ;-) At least Intel's demo code seems to assume so.

I would also suggest to add an '8' to the KREG list [here](https://github.com/CNugteren/CLBlast/blob/CLBlast-257-intel-subgroups/src/tuning/kernels/xgemm.hpp#L135) for better performance (at least on my device). I get around ~230 GFLOPS now with Beignet on the Skylake GT2 GPU.

**Comment by kodonnell** [comment]
Here's the reason for `8`, I think:

> This kernel is compiled to SIMD-8, thus the subgroup size is 8.

See [here](https://software.intel.com/en-us/articles/sgemm-for-intel-processor-graphics) - some good documentation and code examples too. I don't know what 'compiled to SIMD-8' means, and whether it can change per device, but hopefully it makes sense to you.

> it works only for cases where NWG/NDIMC is equal to the subgroup size and MDIMC is larger than the subgroup size.

OK, I ran the tests, and got some improvement, but still half of the intel one (4-500 GFLOPs). 

```
* Found best result 8.99 ms: 238.9 GFLOPS
* Best parameters: GEMMK=1 KREG=4 KWG=1 KWI=1 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=64 PRECISION=32 SA=0 SB=0 STRM=0 STRN=0 VWM=4 VWN=4
```
I wanted to try it with all configurations, so just removed [this check](https://github.com/CNugteren/CLBlast/blob/2965b87dda80ca22bf12527755ef9f3cb5fed46b/src/kernels/level3/xgemm_part1.opencl#L124-L127) and ran it - however this make the above test invalid (`L2 error 3.56e+05 | <-- skipping`). Why is this? Given that condition shouldn't hold, I can't see why removing it makes any difference. In addition, only 8 of the configurations (below) result in `results match` ... which don't obey these constraints, but seem to work anyway.

```
|  205 |   588 |    1   32   16    1    8   16    8   16    1    1    1    0    0    0    0    1 |   OK    232 ms |     99.59 ms |   21.6 |     results match |
|  206 |   588 |    1   32   16    1    8   16    8   16    1    1    1    0    0    0    0    2 |   OK    236 ms |    129.82 ms |   16.5 |     results match |
|  207 |   588 |    1   32   16    1    8   16    8   16    1    1    1    0    0    0    0    4 |   OK    241 ms |    104.19 ms |   20.6 |     results match |
|  208 |   588 |    1   32   16    1    8   16    8   16    1    1    1    0    0    0    0    8 |   OK    258 ms |     95.90 ms |   22.4 |     results match |
|  409 |   588 |    1   64   16    1    8   16    8   16    1    1    1    0    0    0    0    1 |   OK    268 ms |    128.52 ms |   16.7 |     results match |
|  410 |   588 |    1   64   16    1    8   16    8   16    1    1    1    0    0    0    0    2 |   OK    273 ms |    174.84 ms |   12.3 |     results match |
|  411 |   588 |    1   64   16    1    8   16    8   16    1    1    1    0    0    0    0    4 |   OK    290 ms |    162.77 ms |   13.2 |     results match |
|  412 |   588 |    1   64   16    1    8   16    8   16    1    1    1    0    0    0    0    8 |   OK    325 ms |    183.27 ms |   11.7 |     results match |
```

Also, note that even with your original code, I am seeing some skipped results, which maybe indicates there are other cases where it isn't appropriate? Or this this expected?
```
|  143 |   588 |    1   16   64    1    8    8    8    8    1    1    1    0    0    0    0    1 |   OK    254 ms |     22.57 ms |      - | L2 error 3.57e+05 | <-- skipping
|  144 |   588 |    1   16   64    1    8    8    8    8    1    1    1    0    0    0    0    2 |   OK    240 ms |     17.59 ms |      - | L2 error 3.57e+05 | <-- skipping
|  145 |   588 |    1   16   64    1    8    8    8    8    1    1    1    0    0    0    0    4 |   OK    244 ms |     11.62 ms |      - | L2 error 3.57e+05 | <-- skipping
|  146 |   588 |    1   16   64    1    8    8    8    8    1    1    1    0    0    0    0    8 |   OK    262 ms |     12.77 ms |      - | L2 error 3.57e+05 | <-- skipping
|  147 |   588 |    1   16   64    1    8    8    8    8    1    2    2    0    0    0    0    2 |   OK    230 ms |     15.37 ms |      - | L2 error 3.57e+05 | <-- skipping
|  148 |   588 |    1   16   64    1    8    8    8    8    1    2    2    0    0    0    0    4 |   OK    236 ms |     10.59 ms |      - | L2 error 3.57e+05 | <-- skipping
|  149 |   588 |    1   16   64    1    8    8    8    8    1    2    2    0    0    0    0    8 |   OK    244 ms |     12.55 ms |      - | L2 error 3.57e+05 | <-- skipping
```

I will look more tonight.

**Comment by kodonnell** [comment]
Following on `8` - looks like the SIMD-width can vary on Intel devices (and depends on the kernel etc.) ... but [you can determine it](https://stackoverflow.com/questions/7093488/opencl-how-to-i-query-for-a-devices-simd-width#comment84841459_42396258).

**Comment by CNugteren** [comment]
Thanks for testing & for the feedback.

> This kernel is compiled to SIMD-8, thus the subgroup size is 8

About the size 8, we just have to live with it I guess and hope that Intel doesn't change it. Even if the hardware has wider SIMD units, it doesn't mean they have to change the OpenCL subgroup size. The only valid way to test is as I described, but is OpenCL 2.0 and still quite tricky to integrate nicely. So I will leave it at this for now, the tuner will filter out broken kernels if things turn out to be different in different use-cases.

> OK, I ran the tests, and got some improvement, but still half of the intel one (4-500 GFLOPs).

You got 238 GFLOPS, whereas with Intel's `L3_SIMD_4x8x8` kernel you got 308 GFLOPS if I am correct? So that's a lot closer than before. But with the right tuning parameters it should be the same kernel conceptually. Did you try with KREG=8 as I suggested? I get my best result with:
```
GEMMK=1 KREG=8 KWG=1 KWI=1 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=64 PRECISION=32 SA=0 SB=0 STRM=0 STRN=0 VWM=4 VWN=4
```
Which mimics Intel's `L3_SIMD_4x8x8` parameters if I am not mistaken.

> I wanted to try it with all configurations, so just removed this check 

That check is there for a reason, don't remove it! :-) What you are experiencing is that the reference kernel produces incorrect results, and thus most other kernels are 'wrong', except for some which produce the same incorrect results as the reference.

> Also, note that even with your original code, I am seeing some skipped results

I also see a few on my device. I couldn't explain it. Perhaps the subgroup size is not 8 for those scenarios? It could be, because it is kernel independent. Anyway, not super important imho, that's why the tuner has verification of the results.

**Comment by kodonnell** [comment]
OK, looks like I was getting my apples and oranges confused. Running with `KREG=8` enabled, and arguments comparable to the Intel example (i.e. just matrix multiplication of square matrices size=512):
```
./clblast_tuner_xgemm -m 512 -n 512 -k 512 -alpha 1 -beta 0
...

* Found best result 0.72 ms: 372.1 GFLOPS
* Best parameters: GEMMK=1 KREG=8 KWG=1 KWI=1 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=64 PRECISION=32 SA=0 SB=0 STRM=0 STRN=0 VWM=4 VWN=4
```

That's getting close to the 401 GFLOPS I'm getting with NEO (faster than original issue?) and the Intel example for `L3_SIMD_4x8x8`.  Alpha and beta don't change things much (except for which params are fastest) - it just seems to be the matrix size. Anyway - a good result!

The 238 GFLOPS was default options (notably matrix size = 1024), and I'm pretty sure it was with `KREG=8`. I'm having trouble reproducing, as the tuner is hanging at a specific points with `KREG=8`. If I manually skip these, then I get the same result (both GFLOPS and which config was fastest - notably `KREG=4`).

That said, the Intel example gives 126 GFLOPS for `L3_SIMD_4x8x8` and size = 1024, so CLBlast is already beating it. (Just to be fair to intel, other kernels are faster for size = 1024.)

Question: did you set m/n/k/alpha/beta in your test?

> What you are experiencing is ...

Ah, that makes sense. I assumed the reference was a naive CPU implementation.

> Anyway, not super important imho, that's why the tuner has verification of the results.

Except that these errors might be dependent on the size of the matrices (??), in which case you'd need to tune for every size, etc.

Out of interest, do you know how hard it is to implement the Intel `block_read_...` kernels? They're 10-15% faster than `L3_SIMD_4x8x8` for me.

**Comment by CNugteren** [comment]
> That's getting close to the 401 GFLOPS I'm getting with NEO (faster than original issue?) and the Intel example for L3_SIMD_4x8x8. Alpha and beta don't change things much (except for which params are fastest) - it just seems to be the matrix size. Anyway - a good result!

Good to hear :tada: 

> Question: did you set m/n/k/alpha/beta in your test?

I just set used the default values, so m=n=k=1024 and alpha=beta=2. With 512 I actually get quite a bit less, only ~185 GFLOPS. The kernel itself doesn't optimize for zero-valued alpha/beta, so that shouldn't matter at all. The size of the matrices might influence of course. Keep in mind that a matrix of 1024x1024 of floats is only 4MB and might thus benefit from the L3 cache on chip quite a bit (or might fit entirely depending on your hardware). When going to smaller sizes, they might entirely fit in the cache, causing performance to change quite a lot potentially. So that's something to take into account.

> Except that these errors might be dependent on the size of the matrices

Hopefully not. But that's where the regular CLBlast tests come in, they will test all kind of sizes. So first run the tuners, update the C++ code (e.g. run the python database script), and then run the CLBlast tests.

> Out of interest, do you know how hard it is to implement the Intel block_read_... kernels? They can be a lot faster than L3_SIMD_4x8x8 for me (especially as the size varies).

The `MediaBlockRW_SIMD_2x32` kernel for example is just a variation of the other if I am correct, so it should be captured by the tuning parameters. What makes it faster is that it uses 'images' (which might be cached in certain locations) rather than regular OpenCL memory. And that's something the user of the CLBlast API has to do in principle. But I also see some specific image loading/writing stuff in there. So perhaps making CLBlast suitable for images is another topic I could pursue... but for most devices it doesn't matter much, also for Intel it seems to gain at most ~20% or so, right? Not sure if this will be high priority for me, I am already happy with what we have achieved :-)

**Comment by kodonnell** [comment]
> The MediaBlockRW_SIMD_2x32 kernel for example is just a variation of the other if I am correct, so it should be captured by the tuning parameters.

I'm not sure. The code [here](https://software.intel.com/en-us/articles/sgemm-for-intel-processor-graphics) has more examples of variations - if the tuner captures all of them, great! They note there that it depends quite a lot on size.

> What makes it faster is that it uses 'images' ...  also see some specific image loading/writing stuff in there

I think that's part of it - I'd have to check, but there are some intel extensions used for batch reading/writing which might only apply to images.

> Not sure if this will be high priority for me, I am already happy with what we have achieved :-)

Agreed and agreed - it was nice to get such a performance boost with relatively minor changes.

I'm happy to close this issue now, or can leave it to you to close when you merge into master etc.

**Comment by CNugteren** [comment]
Yes, I agree, I would have to look a bit closer to see what else those kernels do. But that's for another time I suppose.

I'll close this issue when the branch is merged into master. One thing perhaps you can still do before that is to run the tuners for the GEMM kernel for and upload the JSON file(s) here. Then I can add that to the database.

**Comment by CNugteren** [comment]
I would actually suggest not to use NEO for now. It is still very new and experimental, and is not something most users will use, since it is not standard nor easily installable in common distributions such as Ubuntu. Could you perhaps run the tuner with the regular Intel OpenCL or (even better) Intel's Beignet?

**Comment by kodonnell** [comment]
> nor easily installable in common distributions such as Ubuntu

FYI that I installed it with no problems on 16.04, with just a few commands (though it did take ages to compile).

> Could you perhaps run the tuner with the regular Intel OpenCL or (even better) Intel's Beignet

Sure, I'll install beigenet and run the tuners, hopefully in the next few days.

**Comment by CNugteren** [comment]
> Sure, I'll install beigenet and run the tuners

Or perhaps just the regular Intel OpenCL? We can also leave it open for now. I'm just saying this because Intel's NEO is still very new, not friendly to compile from source yet ([also experienced an issue](https://github.com/intel/compute-runtime/issues/40)), and results in segfaults apparently.

Thus it would make more sense to tune with a platform most people use. But ideally the platform shouldn't matter too much (but in practice it can matter quite a bit).

So I'll merge this branch is to master today and then we can tune at a later stage, either using Neo if that seems to work well or with another platform.

**Comment by kodonnell** [comment]
> but in practice it can matter quite a bit

Yup, beignet 1.3.1 is around 10-20% slower for sgemm, on both CLBlast and the Intel examples. Is the tuning specific to driver? If not, might be a nice feature.

> Or perhaps just the regular Intel OpenCL? 

I might try that as well, though it might not be worth the hassle of reinstalling.

Re beignet, quoting [here](https://01.org/beignet).

> Beignet vs. NEO
> Starting in Q1’2018, Beignet has been deprecated in favor of NEO OpenCL driver (https://01.org/compute-runtime).
> We encourage the existing Beignet community members to explore the new driver stack and provide feedback.
> Beignet remains our recommended solution for legacy HW platforms (e.g. Ivybridge, Sandybridge, Haswell).

Re

> Intel's NEO is still very new, not friendly to compile from source yet (also experienced an issue)

According to [here](https://www.phoronix.com/scan.php?page=article&item=intel-neo-opencl&num=1) it's "fairly straight-forward", and it was actually easier for me to compile this than beignet or Intel OpenCL. Though I'm gen8, and you're gen9, so maybe there's a difference.

> and results in segfaults apparently.

True, though we're yet to see if it happens to you too. Also, I've had problems before with the Intel OpenCL driver and CLBlast - so it might be my device, or it might be CLBlast, That said, apparently one of the new parts of NEO (despite being based on the old Intel OpenCL SDK etc.) is the GMMLIB graphics memory management library ... which links up nicely to my bug.

Also - I got segfault using beignet, though in different places (running some of the tuners). I manually ran the precision=32 tuners with beignet, and will add the results to issue #1.

**Comment by CNugteren** [comment]
> Is the tuning specific to driver? If not, might be a nice feature

It is not, but in this case it seems to be the case, since the new driver identifies my hardware with a new name. So quite messy, but it does what you want in this case ;-)

And indeed, Beignet is also not that great. Intel is making a nice mess here. Hopefully it will be better in a few years. It's good that they open-sourced everything for Linux.

**Comment by kodonnell** [comment]
>  It's good that they open-sourced everything for Linux.

Yes, water under the bridge and all that, and let's hope it's better in future.

Closing as we (you) have made good progress. There's always other stuff we could optimise further for Intel, but that can happen in a new issue, I think.
