### ISSUE TITLE
Tuning constraint for checking local memory size removed?

### ISSUE THREAD

**Issue by RichardSchulze** [CNugteren/CLBlast#266]
I noticed that in the current version there is no more constraint for checking the local memory size of a configuration. Is that correct?
Out of interest, is there any particular reason why you removed that constraint? In my experience it doesn't noticeably slow down the generation of the search space but should make a difference in search space size and therefore benefit the tuning. Am I missing something?
Many thanks in advance!

**Comment by CNugteren** [comment]
You are right, that constraint was removed. It was not removed on purpose, but it was rather not added when changing the tuner from the external CLTune to something integrated into CLBlast. I thought it not necessary in the sense of correctness because just before launching the kernel it checks anyway, but you have a point about the tuning space and the overhead of compiling useless kernels.

I'll see if it is easy to re-add.

**Comment by CNugteren** [comment]
Let's keep it open, it is nice to have probably :-)

**Comment by CNugteren** [comment]
This feature is now re-added! Let me know if you find any issues.
