### ISSUE TITLE
Tuning specific to platform/driver

### ISSUE THREAD

**Issue by kodonnell** [CNugteren/CLBlast#278]
As per [here](https://github.com/CNugteren/CLBlast/issues/257#issuecomment-385504692), it might be nice to support tuning per driver, i.e. I could tune my device for each driver, and save the results to the database - and then, depending on which driver I choose, the appropriate tunings are used.

Why?

- So I get the best performance on my device (since it differs per driver) - especially for e.g. Intel, which has quite a few drivers out there. The best driver might differ per kernel. 
- So I can get it to run on my device (some kernels might work on some drivers and not others, etc.)

There are two main issues I see here:

- Allowing the database to store multiple results per device (i.e. one per driver).
- More complex (and maybe not a good idea)x: allowing the tuner to select the best driver at runtime. This shouldn't be too hard, except that multiple platforms might need to be initiated beforehand. One can envisage a simple change in API though i.e. 'platform=1,3' to mean 'use platform 1 or 3, whichever is fastest', etc. I don't know if there are other considerations around using multiple platforms at the same time.

**Comment by CNugteren** [comment]
I appreciate the feedback and the time you invest in CLBlast, but I am afraid I have to close this issue, at least for now, for two reasons:

1. I don't see a common use-case here. First of all most vendors have one driver series, hopefully not with too many performance regressions. Second, in case there are different drivers, they should result in more or less the same optimal parameters. In the case that's not true, performance impact should probably not be so big, and if so there are ways around it: A) install the other driver, or B) tune yourself and either update the code or use CLBlast's runtime tuner API. That's for power-users, but that seems to be the scenario you describe.
What you mention about selecting a driver at run-time is another topic and beyond CLBlast imho: the user of the library has to do that, since he/she will determine the platform and has to allocate memory there as well.
 
2. CLBlast is a free time project for me that I do next to a full time job, so I have to prioritise. This issue seems to be a task with a large scope but with benefits only for a few corner cases. For now I have to focus on other more urgent and more impactfull things, such as tuning for different input size. I hope you understand.

So perhaps this will be re-opened later (e.g. in a year or so) if there is more time from my side. Or by some-one else who wants to pick this up.

**Comment by kodonnell** [comment]
That's fine with me. I'll close the issue, and it can always be reopened in future if needed.
