### ISSUE TITLE
Blas Level-X Cholesky CPOTRF?

### ISSUE THREAD

**Issue by JishinMaster** [CNugteren/CLBlast#299]
Hi,
I need to use the cpotrf function. I am currently using clMAGMA, which has not been updated for over 3 years and is based on a outdated version of MAGMA. The performances on GPUs are really bad, yet the CUDA version of cpotrf shows the opposite. It seems that this implementation goes back and forth between the GPU and the CPU.

Are there any plan to port the cpotrf (or cportf_batch) function in CLBlast?

Many thanks!

**Comment by CNugteren** [comment]
No, there are no such plans. However, if I look at the clMagma code (`src/cpotrf.cpp`) it look like it just mostly calls to BLAS functions in a loop. You could mimic that code and call CLBlast instead?

**Comment by JishinMaster** [comment]
Hi,

Thank you for the info.
The annoying part at the moment are the calls to some fortran code running on cpu.

The batch version does not make such calls, but only support MagmaLower at the moment.
An alternative would be to port the batched function to OpenCL.

**Comment by CNugteren** [comment]
I am closing this issue. I think the scope of CLBlast is already large enough (more time required than I have) and this is clearly something for LAPACK, which CLBlast is not, sorry. Until there is a good clMAGMA alternative, copying `src/cpotrf.cpp` from that library and making calls to CLBlast rather than clBLAS is the solution.
