### ISSUE TITLE
Conjugate flag does not have any effect in Omatcopy when m == n

### ISSUE THREAD

**Issue by alexey-morozov** [CNugteren/CLBlast#306]
When CLBlastComatcopy or CLBlastZomatcopy is executed with a_transpose==CLBlastTransposeConjugate and m==n, the computed result is transposed without conjugation. After looking at the code I found out that in this case TransposeMatrix kernel is used (function PadCopyTransposeMatrix in common.hpp, line 88) and that particular kernel implemented in transpose_pad.opencl (line 176) does not handle conjugation at all.

**Comment by CNugteren** [comment]
Well spotted! Actually, the OMATCOPY unittest is wrong, because it does pass, but it doesn't actually do the complex conjugate either. I've added that, then indeed found the tests failing. I've fixed it according to your suggestion, you can find the new code in the `CLBlast-306-omatcopy-conjugate` branch. Could you try again? If all is well I'll merge it into master.

**Comment by alexey-morozov** [comment]
I tried omatcopy in CLBlast-306-omatcopy-conjugate branch - my tests passed.
Thanks a lot!
