### ISSUE TITLE
Event returned by strsv

### ISSUE THREAD

**Issue by ranocha** [CNugteren/CLBlast#311]
I'm writing a wrapper of CLBlast in Julia which can currently be found at https://github.com/ranocha/CLBlast.jl. Using the C interface, the `event` returned by `strsv` is still `NULL` (see https://gist.github.com/ranocha/d249a7b698c36687ce34d4255d2b4c0d#file-strsv-c). This seems to be a bit strange for me, since `event` is not `NULL` for the other methods such as `sgemv` (see https://gist.github.com/ranocha/d249a7b698c36687ce34d4255d2b4c0d#file-sgemv-c). Waiting for a `NULL` event in Julia (via [OpenCL.jl](https://github.com/JuliaGPU/OpenCL.jl])) yields an error. I would consider this behaviour to be a bug, since one cannot wait for the completion of `strsv`.

There might be the same error for `strsm`, since the wrapper throws the same error.

**Comment by CNugteren** [comment]
You might be right. I just checked `TRSV` and `TRSM`, and they both don't contain a reference to the `event_` variable, which is the one the user passed in. It might not be trivial to fix, because these routines runs multiple optional kernels (even other routines as well), and it could end at many places. The final event returned should be of the last kernel: other events are linked to it. I'm a bit busy this weekend, but I'll see what I can do afterwards.

**Comment by CNugteren** [comment]
I just had a look and found it it is not trivial to make the code asynchronous, since it calls the GEMV/GEMM routines, which don't have an interface to pass an event wait list and so on. But I guess keeping it (mostly) synchronous is OK, as it is not really a super optimised routine anyway in CLBlast.

I've made the last operation (copy) asynchronous and added the event there for both TRSV and TRSM. It should now at least not be a nullptr. Here is the branch name `CLBlast-311-missing-event-in-trsv-trsm`, could you try it out for me?

**Comment by ranocha** [comment]
Yes, it works for me. Thank you very much!
