### ISSUE TITLE
global and local thread size in xgemm.cpp

### ISSUE THREAD

**Issue by joye** [CNugteren/CLBlast#314]
should the global size need to m_ceiled / db_["WGD"] and n_ceiled / db_["WGD"] ? why need multiply with MDIMCD and NDIMCD respectively?

```
  const auto m_ceiled = Ceil(m, db_["WGD"]);
  const auto n_ceiled = Ceil(n, db_["WGD"]);
  const auto global = std::vector<size_t>{
  //  CeilDiv(m * db_["MDIMCD"], db_["WGD"]),
  //  CeilDiv(n * db_["NDIMCD"], db_["WGD"])
      (m_ceiled * db_["MDIMCD"]) / db_["WGD"],
      (n_ceiled * db_["NDIMCD"]) / db_["WGD"]
  };
  const auto local = std::vector<size_t>{db_["MDIMCD"], db_["NDIMCD"]};

  // Launches the kernel
  RunKernel(kernel, queue_, device_, global, local, event_); 
```

**Comment by CNugteren** [comment]
I'm not sure exactly what you are asking. The MDIMCD and NDIMCD parameters are the amount of threads per work-group in both dimensions, whereas the WGD parameter is the amount of 'work' done per work-group. Dividing the two thus gives us the amount of threads to launch.

Could you be more specific and suggest the code you expected?

**Comment by joye** [comment]
Thanks for your explanation, I understand now.

**Comment by CNugteren** [comment]
First of all I doubt there is such a big bug in the code, since all tests pass on many devices and performance also matches expected performance.

What you refer to as `idm` and `idn` matches the expectation, right? The group ID is multiplied by WGD (the amount of work per group), and the local ID is multiplied by the MWID (the amount of work per thread). And then later in the code a value between 0 and MWID-1 is added to get the full range.

Although not really 100% matching for the direct version of the GEMM kernel which you are now talking about, perhaps [figure 2 in this paper](https://arxiv.org/pdf/1705.05249.pdf) or [my GEMM tutorial](https://cnugteren.github.io/tutorial/pages/page1.html) will help you understand it better?

**Comment by joye** [comment]
![1743611995](https://user-images.githubusercontent.com/1277051/44938234-25832080-adb0-11e8-9f78-eaa909de05af.jpg)
`idm` and `idn` first operation is group ID multiplied by WGD, then get subgroup in one WGD; if the group num is  `(m_ceiled) / db_["WGD"]`, this formula will get WGD's number in m dimension. Now the group num is  `(m_ceiled * db_["MDIMCD"]) / db_["WGD"]`, which get whole thread's number in m dimension, if now multiply with WGD, will launch more threadgroup than needed.

**Comment by CNugteren** [comment]
Aren't you perhaps confused with OpenCL vs CUDA and the fact that the global size specified here in the host is the total number of threads rather than the number of workgroups?

**Comment by joye** [comment]
Yes, this is the reason, I understand now. I always use the CUDA semantics.
