### ISSUE TITLE
Matrix sum across rows and columns seperately

### ISSUE THREAD

**Issue by praisethemoon** [CNugteren/CLBlast#349]
Hi there, 

I want to first share some love for this library, really well organized and clear API. Thanks for that.

I am working on a ML library where I process a lot of matrices and vector and I have been using library for most of the hard work honestly 🤣 .

I have been writing some very unoptimized OpenCL kernels for  operations that are not-implemented here , yet I am stuck in computing sum of a matrix across various Axes which computes sum of row elements or column ones. 

I wanted to know if you are planning to add such features so I can kinda skip them for the moment, or if you have any tips on implementing them that would be really great!

Cheers.

**Comment by CNugteren** [comment]
Happy to hear you are satisfied with the library :slightly_smiling_face: 

To be clear, I understand that you have a 2D matrix and want to sum in either one of the two dimensions, resulting in a 1D vector of summed rows or columns. In that case, you can of course call the XSUM routine from CLBlast in a loop, but probably that won't be the most efficient.

To make it more efficient, you can probably 'batch' that routine, by adding a second thread dimension and using that to compute a 'batch' offset in the kernel. That way you'll launch only two kernels (XSUM routine uses two kernels) and get the final result without a loop. However, I think that will only be efficient in the case where you are summing in the first dimension in memory (e.g. a row in case of row-major layout).

**Comment by gjvdbraak** [comment]
One option to sum all rows or columns in a matrix is to use a matrix-vector multiplication (xGEMV) where the vector consists of all 1's. To sum in the other direction you just have to set the transpose option in the xGEMV function.

**Comment by CNugteren** [comment]
Thanks @gjvdbraak, I guess that also closes this issue.

For clarity, the solution is to use [CLBlast's GEMV](https://github.com/CNugteren/CLBlast/blob/master/include/clblast.h#L272) routine as follows:
* Feed in your data as the `a` matrix of `m` by `n`.
* Set the `x` vector to a vector of 1's equal to the dimension you want to sum over (either `m` or `n`).
* Use the `a_transposed` option to select the dimension to sum in and depending on how your data is currently layed-out in memory.
* The result will be in the `y` vector.

From the speed perspective it should also be a good solution, since GEMV is memory-bandwidth bound on most architectures, thus the extra loading of the 1-vector should be negligible. This is of course as long as the amount results you produce is not too small compared to the dimension you want to sum over, i.e. the matrix `a` should be much larger compared to the vector `x`.

**Comment by praisethemoon** [comment]
Genius solution I should add! Thanks everyone.
