### ISSUE TITLE
Question - Direct vs. Indirect GEMM kernel source codes

### ISSUE THREAD

**Issue by EvaBasis** [CNugteren/CLBlast#358]
Hello!
First of all congatulations for the great work!

As you mentioned in the documentation, the direct GEMM computes GEMM with one single generic kernel and the indirect GEMM computes GEMM with multiple kernels.
Although, when I open the source codes of the kernels (src/kernels/level3/xgemm_part1-4.opencl for indirect GEMM and src/kernels/level3/xgemm_direct_part1-3.opencl for direct GEMM) I observe that in indirect GEMM there are 3 kernels (XgemmUper, Xgemm, XgemmLower) and inline functions that are called by the kernels. In the other hand in the direct GEMM there are 4 kernels (XgemmDirectNN, XgemmDirectNT, XgemmDirectTN, XgemmDirectTT) and inline functions that are called by the kernels.
I would like to ask why in the direct GEMM there are 4 kernels instead of 1? Is there a choice of 1 kernel out of 4? If yes, where in the source codes is this choise made?

Additionally, I would like to ask the following:
Let's say I have tunned direct GEMM and indirect GEMM for my work size and hardware GPU. As a user how can I specifically choose between direct GEMM and indirect GEMM (in the samples in the code I see only clblast::Gemm for C++ and CLBlastSgemm for C). How do I know that the GEMM routine I called, will call the direct or the indirect kernel?

Thank you in advance!

**Comment by CNugteren** [comment]
> I observe that in indirect GEMM there are 3 kernels (XgemmUper, Xgemm, XgemmLower)

These are for the regular GEMM (`Xgemm`) and specific ones in case we have an upper or lower triangular matrix, not part of the normal GEMM routines, but only for the SYRK, SYR2K, HERK, and HER2K routines. The pre/post processing kernels are found in the `copy_*.opencl` and `transpose_*.opencl` files.

> In the other hand in the direct GEMM there are 4 kernels (XgemmDirectNN, XgemmDirectNT, XgemmDirectTN, XgemmDirectTT)

These are all optimized variants for specific cases: N is for non-transposed and T for transposed, the first letter for the A matrix and the second for the B matrix.

> As a user how can I specifically choose between direct GEMM and indirect GEMM

There is a special [tuner](https://github.com/CNugteren/CLBlast/blob/master/src/tuning/routines/xgemm.cpp) that tunes the `XGEMM_MIN_INDIRECT_SIZE` parameter, which selects for which version of the GEMM kernel to go (direct vs indirect) based on the m*n*k size. I believe this is also explained in the [CLBlast paper](https://arxiv.org/pdf/1705.05249). You can set this parameter programmatically even if you want to have full control.

**Comment by EvaBasis** [comment]
Hello,
thank you for you answer!

As far as the indirect GEMM concerned:
kernels XgemmUpper and Xgemm Lower are not used by the normal GEMM routine. 
So when I run ./clblast_tuner_xgemm those 2 kernels are not running at all.
Is this correct?
Additionally, you mentioned that the normal GEMM kernel is Xgemm that is the regular kernel.
I am confused about what we mean with "regular" kernel.
When I run ./clblast_tuner_xgemm there is a variable GEMMK that determines if the regular or the 2D register tiling kernel will be run (source code refers to them as Kernel 0 and Kernel 1).
So, in part11 and part12 where GEMMK==1 and the kernel 2D register tiling is chosen, what kernel will be run? Still the kernel Xgemm? And the choise between regular and 2D register tiling will be determined by the choise of the different inline functions? 
So with the term 'regular' you do not mean the kernel for GEMMK==0? Is that correct?

Finally I have a last question:
In the part1 and part11 where the exploration is been exhaustivelly, there are some extra constraints (MDIMC=MDIMA, NDIMC=NDIMB, SA=SB,...). Those extra constraints are only to limit the set of options or they additionally have a physical meaning? Either they cannot run because of physical limitations or they do not give efficiency to the opencl code (e.g. MDIMC != MDIMA or SA!=SB  is tested that will not give the best performance)? 

Thank you in advance!

**Comment by CNugteren** [comment]
>  kernels XgemmUpper and Xgemm Lower are not used by the normal GEMM routine.
So when I run ./clblast_tuner_xgemm those 2 kernels are not running at all.
Is this correct?

Indeed.

>  Additionally, you mentioned that the normal GEMM kernel is Xgemm that is the regular kernel.
I am confused about what we mean with "regular" kernel.

I mean regular in terms of GEMM and not a triangular kernel. But yes, `Xgemm` is more specifically the in-direct GEMM kernel as I mentioned earlier. The direct vs in-direct is split in different files, so the filenames should tell you what's going on :-)

>  When I run ./clblast_tuner_xgemm there is a variable GEMMK that determines if the regular or the 2D register tiling kernel will be run (source code refers to them as Kernel 0 and Kernel 1).

`GEMMK` can be seen as yet another tuning parameter for the in-direct GEMM kernel. However, since it changes quite a lot and by lack of a better name, the `GEMMK=1` option was recently introduced to support a second variant of the in-direct `Xgemm` implementation, sharing some of the code. You can see in the sources where the `GEMMK` variable distinguishes the two. But both are in-direct GEMM kernels (making assumptions on e.g. m/n/k sizes, transposing, and ld values and such).

> So, in part11 and part12 where GEMMK==1 and the kernel 2D register tiling is chosen, what kernel will be run? Still the kernel Xgemm? And the choise between regular and 2D register tiling will be determined by the choise of the different inline functions?

A single tuner is for a single kernel, so in all cases with `clblast_tuner_xgemm` it will run the `Xgemm` kernel. The reason the `GEMMK` parameter is not treated like other parameters is that depending on whether that one is set to 0 or 1, other parameters have other meaningful values to set. Different inline functions and/or other pre-processor `#if`'s and `#ifdef`'s if I recall correctly.

>  In the part1 and part11 where the exploration is been exhaustivelly, there are some extra constraints (MDIMC=MDIMA, NDIMC=NDIMB, SA=SB,...). Those extra constraints are only to limit the set of options or they additionally have a physical meaning? Either they cannot run because of physical limitations or they do not give efficiency to the opencl code (e.g. MDIMC != MDIMA or SA!=SB is tested that will not give the best performance)?

There is effectively an infinite number of options to explore, many of which don't work on most devices. So here we limit ourselves to the most sensible cross-device parameters that might yield the best results. But to explore a bit further, we also sample randomly from a much larger parameter space (in the order of 100K - 1M combinations). But of course, if you all the time of the world, you can just try everything. CLBlast will make sure it will discard combinations that don't work on your device.

**Comment by tingxingdong** [comment]
XGEMMUpper XGEMMLower are artificial names. BLAS has standard nama TRMM with a "L" "U" as parameter to differ the shape.  

See LAPACK

http://www.netlib.org/lapack/explore-html/d1/d54/group__double__blas__level3_gaf07edfbb2d2077687522652c9e283e1e.html#gaf07edfbb2d2077687522652c9e283e1e

**Comment by tingxingdong** [comment]
you may want to change XGEMMUpper to TRMM accordingly, therefore.

**Comment by CNugteren** [comment]
Indeed, the XGemmUpper/Lower kernel names might not be the best, but they are not part of the API anyway. I will change them later when I touch them. For now, I believe your question is answered, so I'm closing this issue.
