### ISSUE TITLE
Samples need cl.hpp file.   Maybe add it to the sourcecode, eg in 'thirdparty' directory?

### ISSUE THREAD

**Issue by hughperkins** [CNugteren/CLBlast#36]
Samples need cl.hpp file.   Maybe add it to the sourcecode, eg in 'thirdparty' directory?

(At least, I couldnt figure out how to quickly install it in ubuntu.  I started to google on downloading it, and then just turned samples to 'off'.  but I remember it's just a single file right?  And quite short at that?)

**Comment by CNugteren** [comment]
I agree that this is an issue (actually encountered it today myself as well on a system without `cl.hpp`), but I think it should be solved differently: I don't want to pollute the repository with (large) third-party files. Especially considering that this is just an example, perhaps it would then be better to use the C-API of OpenCL in that case?

As an alternative solution, I've added a line to ask CMake to download the file from the Kronos website whenever the samples are being build. Not ideal of course, since this depends on an internet connection, but I feel this is the best solution. What do you think?

**Comment by hughperkins** [comment]
Your repo is 2.2MB, and cl.hpp is 292KB file, so kind of borderline as far as "large", but I know what you mean.

Depending on an internet connection is not in general an issue, though it can be.

The way I look at it is: you get say 1000 people who come across one's repo.  Each time someone comes across some issue, a certain percentage drop out, maybe 0.5% or 2% or whatever.  The more obstacles that different people come across, the smaller the percentage of people that actually use one's repo finally.  So I try to keep obstacles as few as possible :-)

I've never had anyone say to me "Your repo was 5MB, so I abandoned cloning it!"  :-)  I do get a zillion issues reported with compilers, broken dependencies, missing libraries ...

**Comment by CNugteren** [comment]
It is not just about the size of the repository of course, there are other aspects to consider. But let's leave it like this for now, especially these are just optional samples. And perhaps we'll re-visit this issue later on.
