### ISSUE TITLE
Overflow issue in Program::getIR with a queue created from context with multiple devices

### ISSUE THREAD

**Issue by 9prady9** [CNugteren/CLBlast#391]
The problem was initially reported [here](https://github.com/arrayfire/arrayfire/issues/2919).

The user was trying to use a custom context created out of two NVIDIA GPUs to use with ArrayFire. Though the issue occurred in the call to GEMM API, it should be a problem for other functions as well when a queue is created using a context that contains multiple devices.

The issue stems from [this line](https://github.com/CNugteren/CLBlast/blob/master/src/clpp11.hpp#L513) which assumes that the program object has only one associated device. The number of devices associated to the `cl_program` can be greater than one if the program is created using `clCreateProgramWithSource` which is passed a context that has more than one device.

I tried to come up with a minor patch (given below), but I don't think it is an efficient solution. Hence, raising this issue instead of a PR. The reason I think it may not be efficient is that the patch has an upstream effect of changing the signature of `Program::getIR` method and I am not full aware what consequences that will have. Moreover, the patch also broke tests as I expected since, I am only returning one of the binaries from `getIR()` in the patch.

```diff
diff --git a/src/clpp11.hpp b/src/clpp11.hpp
index aeb1498..2fcab4c 100644
--- a/src/clpp11.hpp
+++ b/src/clpp11.hpp
@@ -508,13 +508,27 @@ class Program {
 
   // Retrieves a binary or an intermediate representation of the compiled program
   std::string GetIR() const {
-    auto bytes = size_t{0};
-    CheckError(clGetProgramInfo(program_, CL_PROGRAM_BINARY_SIZES, sizeof(size_t), &bytes, nullptr));
-    auto result = std::string{};
-    result.resize(bytes);
-    auto result_ptr = result.data();
-    CheckError(clGetProgramInfo(program_, CL_PROGRAM_BINARIES, sizeof(char*), &result_ptr, nullptr));
-    return result;
+    cl_uint num_devices = 0;
+    CheckError(clGetProgramInfo(program_, CL_PROGRAM_NUM_DEVICES,
+                                sizeof(cl_uint), &num_devices, nullptr));
+
+    std::vector<size_t> binSizesInBytes(num_devices, 0);
+    CheckError(clGetProgramInfo(program_, CL_PROGRAM_BINARY_SIZES,
+                                num_devices * sizeof(size_t), binSizesInBytes.data(), nullptr));
+    std::vector<std::string> bins;
+    for (auto binSize: binSizesInBytes) {
+        auto result = std::string{};
+        result.resize(binSize);
+        bins.push_back(result);
+    }
+    std::vector<unsigned char*> out;
+    for (auto bin: bins) {
+        out.push_back((unsigned char*)bin.c_str());
+    }
+    //auto result_ptr = result.data();
+    CheckError(clGetProgramInfo(program_, CL_PROGRAM_BINARIES,
+                                num_devices * sizeof(char*), out.data(), nullptr));
+    return bins[0];
   }
 
   // Accessor to the private data-member
```

**Comment by CNugteren** [comment]
Thanks for the detailed report and already doing most of the investigation :-) I don't have time today, but I will look at this tomorrow in more details.

But at a first glance, since this `GetIR` function is only used to cache whatever is there for the next time, should it be sufficient to just store all the binaries (for both devices) even if they are not used by CLBlast?

The relevant code in `routine.cpp`:
```
  program_ = CompileFromSource(source_string, precision_, routine_name_,
                               device_, context_, options, 0);
  BinaryCache::Instance().Store(BinaryKey{platform_id, precision_, routine_info, device_name},
                                program_->GetIR());
```

**Comment by 9prady9** [comment]
:+1: 

Yes, I did find that section of code. But `GetIR` cannot return single `std::string` it has to be a vector of strings for that to be successfully stored in cache. The cache definition https://github.com/CNugteren/CLBlast/blob/master/src/cache.hpp#L74 should also accept vector of strings right ?

In any case, once you start looking into it, I am sure you will figure out the relevant changes more quickly than me. Thank you.

**Comment by CNugteren** [comment]
I took a more detailed look. First of all, the CLBlast API takes as device-specification argument a command-queue, e.g.:
```
template <typename T>
StatusCode Axpy(const size_t n,
                const T alpha,
                const cl_mem x_buffer, const size_t x_offset, const size_t x_inc,
                cl_mem y_buffer, const size_t y_offset, const size_t y_inc,
                cl_command_queue* queue, cl_event* event = nullptr);
```
And a command-queue is tied to a [single device](https://www.khronos.org/registry/OpenCL/sdk/1.1/docs/man/xhtml/clCreateCommandQueue.html). Therefore, the `GetIR()` function's signature as used in CLBlast should remain the same, but perhaps the implementation should change to take the binary for the right device.

As you rightly said, a context can be for multiple devices. However, although a `cl_program` object is created for a specific context (https://github.com/CNugteren/CLBlast/blob/master/src/clpp11.hpp#L462), when we compile the kernel it is done for a specific device only (https://github.com/CNugteren/CLBlast/blob/master/src/clpp11.hpp#L491). So I don't think that there can be multiple meaningful binaries to choose from. According to the documentation of [clGetProgramInfo](https://www.khronos.org/registry/OpenCL/sdk/1.1/docs/man/xhtml/clGetProgramInfo.html), even though it might return an integer larger than 1 when querying `CL_PROGRAM_NUM_DEVICES`, it should return a binary size of 0 for all but 1 of them when querying for `CL_PROGRAM_BINARY_SIZES`.

So I would suggest to modify your patch slightly and find the first (and the last automatically) binary with non-zero size and return that. If that doesn't work, we can pass in the device ID to `GetIR()` and then query the device ID's using `CL_PROGRAM_DEVICES` so we know which one it is. Since you have a test environment with multiple devices (I don't right now), could you test this out with something along the lines of (based on your code):
```
cl_uint num_devices = 0;
CheckError(clGetProgramInfo(program_, CL_PROGRAM_NUM_DEVICES,
                            sizeof(cl_uint), &num_devices, nullptr));

std::vector<size_t> binSizesInBytes(num_devices, 0);
CheckError(clGetProgramInfo(program_, CL_PROGRAM_BINARY_SIZES,
                            num_devices * sizeof(size_t), binSizesInBytes.data(), nullptr));

auto bytes = size_t{0};
for (auto binSize: binSizesInBytes) {
    if (binSize != 0) { bytes = binSize; }
}

auto result = std::string{};
result.resize(bytes);
auto result_ptr = result.data();
CheckError(clGetProgramInfo(program_, CL_PROGRAM_BINARIES, sizeof(char*), &result_ptr, nullptr));
return result;
```

**Comment by 9prady9** [comment]
Sure, I wasn't sure either about changing the GetIR API. At the same time, I wasn't clear how to get specific device info into that method also without changing the signature. Yeah, I didn't realize the size returned can be zero if that binary isn't compiled for a device as it wasn't given to the `clBuildProgram` call. Good catch on that.

I am going to try your modification today and will keep you posted. There is slight change in that though, we still need to give it an array of `num_devices` pointers, but we can set that particular device pointer NULL that are not needed.

**Comment by 9prady9** [comment]
@CNugteren I have raised the PR #392 Please have a look.
