### ISSUE TITLE
Python scripts fails when using python3

### ISSUE THREAD

**Issue by baryluk** [CNugteren/CLBlast#395]
Python 2 is dead, and not even installed on my Linux distro anymore.

I tried to force it to use python3, and it doesn't have any syntax errors, but some issues remain:

```
$ python3 ../scripts/benchmark/benchmark.py --platform 0 --device 0 --benchmark gemm
../scripts/benchmark/benchmark.py:106: SyntaxWarning: "is" with a literal. Did you mean "=="?
  plot_title = benchmark_name if plot_title is "" else benchmark_name + ": " + plot_title
[benchmark] Running on platform 0, device 0
[benchmark] Running 6 benchmarks for settings 'gemm'
[benchmark] Running benchmark 'gemm:multiples of 128'
[benchmark] Calling binary: ./clblast_client_xgemm -platform 0 -device 0 -precision 32 -runs 20 -warm_up -q -no_abbrv -clblas 0 -cblas 0 -m 128 -n 128 -k 128 -layout 102 -transA 111 -transB 111 -step 128 -num_steps 20
Traceback (most recent call last):
  File "../scripts/benchmark/benchmark.py", line 183, in <module>
    benchmark_single(**parsed_arguments)
  File "../scripts/benchmark/benchmark.py", line 139, in benchmark_single
    result = run_benchmark(bench["name"], bench["arguments"], precision, num_runs_benchmark,
  File "../scripts/benchmark/benchmark.py", line 59, in run_benchmark
    result = utils.parse_results(benchmark_output)
  File "/home/user/vec/CLBLAST/CLBlast/scripts/benchmark/utils.py", line 60, in parse_results
    csv_data = csv_data.split("\n")
TypeError: a bytes-like object is required, not 'str'
```

it appears conversion from bytes to str when parsing data need to be fixed.

Also the `#!/usr/bin/env python` need to be updated to `#!/usr/bin/env python3`, in benchmark, database, generator and few other places and scripts.

**Comment by CNugteren** [comment]
I agree with you that if these scripts would be written today, they would have been written without python2 support. But they are a bit older and they were therefore designed to work with both Python 2 and Python 3. So if you encounter an issue with Python 3, it is a bug, not that it wasn't designed to work with Python 3.

Then about the update request of the shebang, is that really needed or even desired? On newer systems `python` will just point to a Python 3, right? So that will be fine, and this way it will also work on systems that still have Python 2 as the main `python`, right?

I have just tried all 3 scripts, and all work fine with Python 2 and Python 3, except for the benchmark script and indeed it shows that particular issue for me as well. The reason is that the result to parse is now of type bytes rather than string, so that needs to be decoded as ASCII first. I've just fixed that [in this PR](https://github.com/CNugteren/CLBlast/pull/396) (soon to be merged) and tested it with Python 2 and 3.

**Comment by baryluk** [comment]
No, on most systems `python` only points to Python 2. So if you have python3, but no python2, the `python` doesn't exist. Otherwise you might have a silent incompatibilities, by running in the wrong version of python.

**Comment by CNugteren** [comment]
> So if you have python3, but no python2, the python doesn't exist. 

I looked this up and it seems indeed [you are right](https://www.fosslinux.com/39384/switching-between-python-2-and-3-versions-on-ubuntu-20-04.htm) at least for Ubuntu 20.04. So yes that will lead to an error, but you can of course still run the script like so: `python3 ./scripts/generator/generator.py`.

> Otherwise you might have a silent incompatibilities, by running in the wrong version of python.

What is 'the wrong version of Python' here? For you it seems to be Python 2, for others it might Python 3? As said, the code works in both versions, so from my perspective there is no 'wrong version'.

What I propose then is to just remove the shebang line if you think this will cause issues for people, they just have to make it explicit themselves then what Python they want to use, because I don't think there is a [good alternative](https://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take).

**Comment by baryluk** [comment]
`#!/usr/bin/env python3` is the correct way to do it.

I don't see point supporting Python 2.

Any way, I have some other patches to benchmark, and the client.{hpp,cpp} coming. :+1:

**Comment by CNugteren** [comment]
For your machine perhaps, but you have to realize software like CLBlast is often also ran on older and less well supported embedded systems. I think it would be a waste to create potential issues by dropping Python 2 support. If you need to run it with Python3, simply specify so and ignore the shebang.

Other than that, I believe the original issue is fixed so I'll close this issue. Thanks for your contributions.

**Comment by baryluk** [comment]
I highly doubt that this would create any issues really. Python 3 was released 12 years ago. Also, if for some extremely weird reasons they don't have Python 3, they can manually call it using python2. I think it is better than inconvincing majority of users. My proposal is to change it to `python3` in shebang, and see if anybody complains. Sometimes you need to move on.

Thanks for your consideration.

**Comment by CNugteren** [comment]
OK yes I guess you are right that the opposite also holds: putting Python 3 in the shebang doesn't break things on systems with only Python 2, those cases can still work indeed with manually specifying `python` on the command line. Feel free to make a PR to update all 3 scripts.
