### ISSUE TITLE
SGEMM With Small Matricies

### ISSUE THREAD

**Issue by cwbelknap** [CNugteren/CLBlast#408]
Hello,

I have built the CLBast lib for the i.MX6Q (Vivante GC2000 GPU) and I am using the C API.
I am experiencing OpenCL errors when I try to run SGEMM on small (8x8) matrices. 
Specifically: `CLBlast: OpenCL error: clCreateKernel: -5` is thrown  by CLBlastSgemm.

Any guidance or suggestions for debugging? 

Cheers,
Curtis

**Comment by CNugteren** [comment]
Thanks for your interest and good to hear you managed to compile it on the Vivante GPU. However, I'm afraid I have to disappoint you, because I think you might have the same issue that someone else reported a while ago, see #227 and in particular [this comment from me](https://github.com/CNugteren/CLBlast/issues/227#issuecomment-379015426) explaining the situation.

In short: some of CLBlast's kernels are quite big - too big for the instruction cache of the Vivante GPU. The fact that you only see that for particular matrix sizes is that CLBlast doesn't always use the same kernel for each use-case. So a work around would be to change the tuning parameters, as also discussed in the issue mentioned above. Could you have a read through that one and let me know if you have any further questions?
