### ISSUE TITLE
GEMM using Multiple threads

### ISSUE THREAD

**Issue by skn123** [CNugteren/CLBlast#411]
OpenCL has a facility for calling multithreaded applications on the GPU (at least AMD does). Suppose I want to run GEMM in a multithreaded mode, how would I go about doing that? The use would be a parallel inversion of a dense triangular matrix as described in :
http://icl.cs.utk.edu/news_pub/submissions/TriangularLinear%20System%20Solver%20for%20GPU%20with%20CUDA.pdf

**Comment by CNugteren** [comment]
I'm not sure what 'facility' you are talking about, but as far as I'm aware you don't have to do anything special. The library should be thread-safe, just call a CLBlast operation from one (or more) of your threads. Perhaps I don't understand your question?

**Comment by skn123** [comment]
If you look at the paper (or for that matter any Blocked version of Triangular solver), you will notice that after the small triangular components are computed, then the remaining stuff is composed of matrix multiplication (in this case GEMM). There are two versions of this question:
a.) I am not sure if GEMM is designed in such a way that would permit in-place multiplication
b.) The fact that I want to use GEMM is to parallelize the operation. The paper (Steps 1-4) illustrates this.

**Comment by CNugteren** [comment]
OK, I took a look at the poster you referred to, and it seems you want to use GEMM as part of a bigger algorithm. For that you could use CLBlast normally, and as I said it is thread-safe, so you can just call CLBlast normally from as many (CPU) threads as you want.

However, I doubt that you this will be fast, because that means you'll have to run a lot of OpenCL kernels (some after each other as well), and each kernel will have to read from off-chip memory and write the results back. Especially if your GEMMs are small as described in the poster (16x16 or 32x32), I doubt that this is fast. I instead propose that you don't use CLBlast, but rather program your own small GEMM kernels within a larger OpenCL kernel, but I'm not an expert in the problem you are trying to solve.

One other possibility to try is to see if you can phrase your problem as a 'batched' GEMM and use the batched or strided GEMM call from CLBlast, see [here](https://github.com/CNugteren/CLBlast/blob/master/doc/api.md#xgemmbatched-batched-version-of-gemm) and [here](https://github.com/CNugteren/CLBlast/blob/master/doc/api.md#xgemmstridedbatched-stridedbatched-version-of-gemm) or an example [here](https://github.com/CNugteren/CLBlast/blob/master/samples/sgemm_batched.cpp). But again, I don't know if that fits your problem.
