### ISSUE TITLE
Non-absolute level-1 routines

### ISSUE THREAD

**Issue by blueberry** [CNugteren/CLBlast#45]
I know this is not a part of the BLAS standard, but these routines are often needed in practice. I am talking about xSUM, IxMAX, IxMIN.

Having in mind that these routines' implementation is a matter of one abs() call, what do you think of adding those to CLBlast, either through an aditional option in an already existing routine, or as an independent, matching, non-abs routine?

**Comment by CNugteren** [comment]
Indeed, it might be quite trivial to implement these routines. But to test them properly might be a bit trickier, since these routines are not part of clBLAS or any normal BLAS library. Making it an optional argument might not be ideal, e.g. because those routines would then have wrong names (e.g. IxAMAX performing an IxMIN operation). So I would prefer to go for a separate implementation then, perhaps untested or tested against some custom written code?

Do you know of any BLAS-like library where such routines are supported?

**Comment by blueberry** [comment]
Maybe there could be under-the-hood function with parameter, that gets called by xSUM and xASUM. That way, it would be fairly well covered by existing xASUM tests with a possible addition of a few xSUM tests that would cover border cases. Fortunately, the difference is trivial enough that I think xASUM tests and a bit of reasoning on paper can make sure this works well.

About the motivation and need:
1. OSX Accelerate framework has a non-absolute sum function `vDSP_sve`
2. ArrayFire has `sum`
3. Possibly many other high-level libraries and applications roll out their own
4. `sum` and `max` is needed very often. There are even stackoverflow and stackexchange questions where the recommendation is "unfortunately, you must write your own" or "call `dot` with a matching vector of ones". The trouble is - "your own" is 10 times slower than ATLAS or MKL.
5. Today, one of the major use cases of libraries such as CLBlast is for building ML and statistical applications. Both `sum` and `max` are virtually the two most needed functions there. I guess this could be a good motivating factor (although it may not be the main one) for someone to choose CLBlast over some other library.

**Comment by CNugteren** [comment]
OK, thanks for the explanation. I'll put it on my list (let's leave this issue open) and implement it based on the absolute-versions of the functions, without thorough tests (at first at least).

**Comment by blueberry** [comment]
Thank you very much! I didn't mention `min`, but it is in the same bag :)

**Comment by CNugteren** [comment]
I have added an experimental version of 'max' and 'sum' for now, 'min' is a different story since there is no absolute version at all:

```
  * SSUM/DSUM/ScSUM/DzSUM (non-absolute version of the above xASUM BLAS routines)
  * iSMAX/iDMAX/iCMAX/iZMAX (non-absolute version of the above ixAMAX BLAS routines)
```

The routines are not tested through unit-tests, but some of the 'amax' and 'asum' tests should cover them, since they change only in 1 or 2 places.

When you have time, could you test if this is what you wanted?

**Comment by blueberry** [comment]
Thank you. I'll test that as soon as I get back home. Regarding imin, isn't that just imax of -x[gid] or am I missing something?

**Comment by CNugteren** [comment]
You are right. There is now also a `IxMIN` implementation:
```
  iSMIN/iDMIN/iCMIN/iZMIN (non-absolute minimum version of the ixAMAX BLAS routines)
```
