### ISSUE TITLE
xGEMM checks different from cblas

### ISSUE THREAD

**Issue by catalinpadurean** [CNugteren/CLBlast#453]
Is there a reason why CLBlast checks for xGEMM ar different from cblas ?
I was reading the documentation from intel for xGEMM and noticed that the checks for ld_a and ld_b are different from your checks.
I.E: 
1. CLBLast:    When transpose_a == Transpose::kNo, then a_ld must be at least m, otherwise a_ld must be at least k.
                     When transpose_b == Transpose::kNo, then b_ld must be at least k, otherwise b_ld must be at least n.

2. cblas: lda (Specifies the leading dimension of a as declared in the calling (sub)program.)

 - transA=CblasNoTrans && Layout = CblasColMajor: lda must be at least max (1,m)
 - transA=CblasNoTrans && Layout = CblasRowMajor: lda must be at least max (1,k)
 - transA=CblasTrans && Layout = CblasColMajor: lda must be at least max (1,k)
 - transA=CblasTrans && Layout = CblasRowMajor: lda must be at least max (1,m)
 
 Same goes for ld_b.
 I guess what I'm trying to understand is why do you skip the checks for Row/Col Major and cblas doesn't?

**Comment by CNugteren** [comment]
I think this might be a documentation bug in CLBlast. Because when I follow the code, both the layout and the transpose arguments are taken into account when computing whether the matrix is 'rotated' or not (in [ProcessArguments](https://github.com/CNugteren/CLBlast/blob/ef5176dd968dbf9da7c94506fc0d5f8bd463b293/src/routines/level3/xgemm.hpp#L80)). And then given that rotation, the first dimension is computed (e.g. `m` or `k`) (e.g. [here](https://github.com/CNugteren/CLBlast/blob/ef5176dd968dbf9da7c94506fc0d5f8bd463b293/src/routines/level3/xgemm.hpp#L111)), and following that the check against the `ldX` value is made (e.g. [here](https://github.com/CNugteren/CLBlast/blob/ef5176dd968dbf9da7c94506fc0d5f8bd463b293/src/routines/level3/xgemm.cpp#L82)).

I'll work on fixing the documentation bug.
