### ISSUE TITLE
[Question] How to Install on Windows?

### ISSUE THREAD

**Issue by ilovefreesw** [CNugteren/CLBlast#499]
Where is the installation instructions for Windows here: https://github.com/CNugteren/CLBlast/blob/master/doc/installation.md

It only talks about compilation. And download the prebuilt binaries.

I don't understand how to install it from binaries.

What I am supposed to do with these files...

![image](https://github.com/CNugteren/CLBlast/assets/77317006/88038568-eaf2-4018-b3e3-13875265772e)

No setup or no MSI. I actually want to build Whisper.cpp wit it: https://github.com/ggerganov/whisper.cpp#opencl-gpu-support-via-clblast

**Comment by CNugteren** [comment]
I am not a Windows user myself, so I'm not an expert. The most important of what you've downloaded is the file in the `lib` folder, that contains the CLBlast library. Furthermore, since you are compiling another tool as well, you'll need the `include` folder as well. The `bin` folder just contains pre-built binaries that use CLBlast, e.g. with tuners or sample programs. You don't need those.

You'll need to place the `lib` and `include` folders in a location that is accessible by whatever needs it next, in your case `whisper.cpp`. I can't tell you exactly what you need to do, because that depends on how `whisper.cpp` is organized, and how you are compiling `whisper.cpp` (e.g. with MingW, with MSVC, with WSL). You should be able to find plenty of information about this on the internet and/or on the `whisper.cpp` project.

**Comment by ilovefreesw** [comment]
After few hours of research, it turned out I needed this package to install on Windows: https://packages.msys2.org/package/mingw-w64-x86_64-clblast?repo=mingw64

Since I am using Git Bash (from Git for Windows SDK based on MSYS2) to run `make` and `gcc` commands.

Thanks for you for your comment. I have now built whsiper.cpp with OpenBlast now :)
