### ISSUE TITLE
ERROR IN ROCK5b

### ISSUE THREAD

**Issue by superHappy-yo** [CNugteren/CLBlast#547]
![image](https://github.com/CNugteren/CLBlast/assets/59483909/ef1f94b8-b317-408c-88cb-46c990b7ff80)

It don't happened in my compute(Intel),but I copy it to rock5b,and there are errors happend after I compile it and test my code(im2col+gemm).

**Comment by CNugteren** [comment]
Thanks for reporting. The error message is from a simple kernel code pre-processor inside CLBlast. So unless you did something wrong, this is definitely a CLBlast issue. Let's first check if everything went OK on your side. I can find that line 3 times in my `CLBlast/src/kernels/level3/xgemm_direct_part2.opencl` file. Can you double check that that file is complete and correct? It seems from the error log that there might be a `{` missing at the end of `  for (int _kib = 0; _kib < KWBD; _kib += 1) {`, but I can't see that issue locally.

**Comment by superHappy-yo** [comment]
Thanks for reply.
I can run it on my computer,but it couldn't work on rock5b. I used the default  format tool in vscode to format the code. Maybe this action make it error? I check my code and I can run it on my Intel computer(ubuntu).

And I want to add a new function in CLblast.I add a function named "gemmMec" in **Xgemm.cpp**  and add a **gemm_mec.opencl**. It can run correctly. What else do I need to do to make full use of the library and reach the best speed? Can you help me?
![图片](https://github.com/CNugteren/CLBlast/assets/59483909/4c416e60-9bcc-4f11-8d34-ba82d198d353)

**Comment by CNugteren** [comment]
>  I can run it on my computer,but it couldn't work on Radxa ROCK 5B with ubuntu. I used the default format tool in vscode to format the code. Maybe this action make it error? I check my code and I can run it on my Intel computer(ubuntu).

Yes, you should not re-format the OpenCL code. CLBlast contains a very simple pre-processor that makes many assumptions on the code contents and style, this is why the error showed up. So I guess this matter is now solved.

> And I want to add a new function in CLblast.I add a function named "gemmMec" in Xgemm.cpp and add a gemm_mec.opencl. It can run correctly. What else do I need to do to make full use of the library and reach the best speed? Can you help me?

Is this something you want to contribute to the main CLBlast, or is this some very specific kernel of your own? Because if this is your own kernel, I would not recommend adding it to CLBlast directly. Instead you are probably looking for a kernel tuner? So perhaps my own [CLTune](https://github.com/cnugteren/cltune) or the much better [kernel-tuner](https://github.com/KernelTuner/kernel_tuner) can be of help?

In any case I propose to close this issue. If you have questions adding a new feature to CLBlast for public usage, please open a new issue with descriptions about what the function should do, and then we can see whether it makes sense to add it.
