### ISSUE TITLE
Visual Studio support

### ISSUE THREAD

**Issue by hughperkins** [CNugteren/CLBlast#6]
Hi CNugteren,

Per your email just now, a huge chunk of my potentail user-base are Python users, on Windows.  The current version of visual studio for Python 2.7 is Visual Studio 2008.  For Python 3.4, it is Visual Studio 2010.

Pleaes can you confirm that your c++11 version of clBLAS will compile and run correctly using Visual Studio 2008 and Visual Studio 2010.

By the way, what functionalities in C++11 do you see as 'killer functionalities', that are worth throwing away a huge chunk of one's potential userbase for?

Hugh

**Comment by hughperkins** [comment]
PS:
- by the way, I'm happy to see you are provided OpenCL 1.1 compatibility.  I think this is a good thing :-)  (Otherwise it wont run on nvidia right?)
- to answer your question, the clBLAS patch I submitted was as part of my work on porting torch to OpenCL, https://github.com/hughperkins/cltorch

**Comment by CNugteren** [comment]
This preview version has not been tested on Windows, as I don't yet have access to such a system. It will be tested on Windows and Visual Studio before the 1.0.0 release. It will most definitely not compile under VS08 and VS10, since C++11 support is only gradually appearing in the latest releases of Visual Studio.

P.S. Any discussion which is not really a CLBlast 'issue' (such as my motivation to use C++11) can be directed to me per email (found on www.cedricnugteren.nl).

**Comment by hughperkins** [comment]
You skipped my question asking what you see as critical advantages of c++11 :-P  Anyway, closing the issue :-)
