### ISSUE TITLE
Repeated SGEMM calls leak memory

### ISSUE THREAD

**Issue by gcp** [CNugteren/CLBlast#74]
Steps to reproduce:

Take sgemm.cpp from the samples. Put an infinite for() loop around the clblast::Gemm() + clWaitForEvents() calls. Launch the sample and watch it eventually use up all memory.

**Comment by CNugteren** [comment]
You are right, I managed to reproduce it on my system.

This is quite serious, I will investigate it as soon as possible.

**Comment by CNugteren** [comment]
A quick debugging session seems to indicate that the memory leaks originate from the actual OpenCL kernels, so I am not sure this is CLBlast's fault.

I did what you said and added a `while(1)` loop around the GEMM call in the `sgemm.cpp` sample. Then I observed a continuous memory increase indeed. But after I commented out the actual launch of kernels, I didn't see this memory increase anymore. Below is how to reproduce it for GEMM (you need to disable adding those events to the event waitlist because they are null pointers now):
```
diff --git a/src/clpp11.hpp b/src/clpp11.hpp
index f8bc2b0..8ffa51e 100644
--- a/src/clpp11.hpp
+++ b/src/clpp11.hpp
@@ -658,9 +658,9 @@ class Kernel {
   // Launches a kernel onto the specified queue
   void Launch(const Queue &queue, const std::vector<size_t> &global,
               const std::vector<size_t> &local, EventPointer event) {
-    CheckError(clEnqueueNDRangeKernel(queue(), *kernel_, static_cast<cl_uint>(global.size()),
-                                      nullptr, global.data(), local.data(),
-                                      0, nullptr, event));
+    //CheckError(clEnqueueNDRangeKernel(queue(), *kernel_, static_cast<cl_uint>(global.size()),
+    //                                  nullptr, global.data(), local.data(),
+    //                                  0, nullptr, event));
   }
 
   // As above, but with an event waiting list
diff --git a/src/routines/level3/xgemm.cpp b/src/routines/level3/xgemm.cpp
index 9ea5559..9c2d504 100644
--- a/src/routines/level3/xgemm.cpp
+++ b/src/routines/level3/xgemm.cpp
@@ -139,7 +139,7 @@ StatusCode Xgemm<T>::DoGemm(const Layout layout,
                                       ConstantOne<T>(), program,
                                       true, a_do_transpose, a_conjugate);
       if (ErrorIn(status)) { return status; }
-      eventWaitList.push_back(eventProcessA);
+      //eventWaitList.push_back(eventProcessA);
     }
 
     // As above, but now for matrix B
@@ -151,7 +151,7 @@ StatusCode Xgemm<T>::DoGemm(const Layout layout,
                                       ConstantOne<T>(), program,
                                       true, b_do_transpose, b_conjugate);
       if (ErrorIn(status)) { return status; }
-      eventWaitList.push_back(eventProcessB);
+      //eventWaitList.push_back(eventProcessB);
     }
 
     // As above, but now for matrix C. This is only necessary if C is used both as input and output.
@@ -163,7 +163,7 @@ StatusCode Xgemm<T>::DoGemm(const Layout layout,
                                       ConstantOne<T>(), program,
                                       true, c_do_transpose, false);
       if (ErrorIn(status)) { return status; }
-      eventWaitList.push_back(eventProcessC);
+      //eventWaitList.push_back(eventProcessC);
     }
 
     // Retrieves the Xgemm kernel from the compiled binary
@@ -195,7 +195,7 @@ StatusCode Xgemm<T>::DoGemm(const Layout layout,
 
       // Runs the post-processing kernel if needed
       if (!c_no_temp) {
-        eventWaitList.push_back(eventKernel);
+        //eventWaitList.push_back(eventKernel);
         status = PadCopyTransposeMatrix(queue_, device_, context_, db_, event_, eventWaitList,
                                         m_ceiled, n_ceiled, m_ceiled, 0, c_temp,
                                         c_one, c_two, c_ld, c_offset, c_buffer,
```

**Comment by gcp** [comment]
I can sort of confirm this. I tried valgrinding the problem on a Linux system, but all the leaks that were found are in the nvidia driver (proprietary - which makes it hard to see what's going on), and didn't seem to be in CLBlast. Maybe beignet or radeon + mesa + clover have symbols that would allow tracking it down, but I can't verify that right now.

That being said, I see this leakage **both** on a Windows system with AMD Crimson, and on a Linux system with NVIDIA's proprietary driver. So it's still a problem you'll have to fix or work around.

This isn't a problem with those wrappers around event not calling clReleaseEvent or something? That looks like the only place where the kernels allocate in a user-visible way, and I guess valgrind won't understand the need to call clReleaseEvent to stop leaks, so maybe that wouldn't show up...

**Comment by CNugteren** [comment]
I also verified that the issue is also on OS X, so it doesn't seem to be platform specific. Indeed, valgrind doesn't help much here, and since the C++ code only uses smart pointers and STL containers I thought memory leaks wouldn't occur.

But I didn't know about `clReleaseEvent`, so that might indeed be the issue. The reason I didn't know it existed is because there is no `clCreateEvent` or something similar as far as I am aware. I'll see if I can fix it.

**Comment by blueberry** [comment]
If I remember well, almost all objects in OpenCL have to be released explicitly. The exceptions are platform and root level device.

**Comment by CNugteren** [comment]
OK, so I just made commit 7cf2f8c2 to the `development branch. There are three types of events in CLBlast as far as I can see:

1. Internal events used only for one single kernel launch. These events are now properly cleaned-up afterwards due to an std::shared_ptr with a custom destructor. This should be sufficient since these events are only used once ever.
2. An outside event passed on by the user to one of the CLBlast calls. It is the responsibility of the user to clean that one up. I've added several `clReleaseEvent` calls to the samples. Note that if you construct a for/while loop around a GEMM call you should also include the `clReleaseEvent` within the loop as far as I understand.
3. If an outside event is not passed by the user, a default event is created. In this case it is the responsibility of CLBlast to clean it up. I am not sure how to distinguish between this type of event and one of the above type 2. So right now this would still leak memory, but this scenario is not part of your example.

Despite the fixes for 1 and 2 I still see memory growing over time, although a lot slower than before. Could you perhaps also test on your system if the leak is still present but not as severe as before?

Also, I couldn't find any `clReleaseEvent` calls in clBLAS, except for in the samples and tests. So I am curious how they handle this issue.

**Comment by gcp** [comment]
> Also, I couldn't find any clReleaseEvent calls in clBLAS, except for in the samples and tests. So I am curious how they handle this issue.

If they don't pass any ptr-to-event into the enqueueNDRangeKernel calls unless it's a user passed one, there's simply never anything for them to free up.

In your code, the issues are the:

auto eventKernel = Event();

which are then used for:

eventWaitList.push_back(eventKernel);

But note that adding these is completely unnecessary unless the queue being used is out-of-order. Even if it is out-of-order, you can queue barriers and force serialization in your code. 

It's possible clBlas would fail when given an out-of-order queue? When looking at their xgemm.cc, notice that eventWaitList is not modified at all even when consecutive kernels are being enqueued.

**Comment by gcp** [comment]
> Could you perhaps also test on your system if the leak is still present but not as severe as before?

It still leaks, but not on every run, and not in debug mode. I'm not sure what's up with that. I did change clp11.hpp line 692 to just pass nullptr instead of event, and that stops the leaking. So it looks like it's still some issue with events?

**Comment by CNugteren** [comment]
Indeed, setting that to a `nullptr` stops the memory leaks. But I am not sure what could be the cause, because all events are now released. I checked with print-statements that the events used in `enqueueNDRangeKernel` calls are released with `clReleaseEvent`, which matches 1 to 1.

About your out-of-order remarks: yes, perhaps it is also possible to do without internal events. But if you want to give the user an option to pass or not to pass an event, then I am still not sure how to distinguish and properly clean it up if the user didn't pass an event. Normally you would check for `nullptr` or something, but the user's event might be a `nullptr` as well because it is an output argument, not an input argument. Anyway, that's a different issue.

I'll keep digging to see what else could cause this issue.

**Comment by gcp** [comment]
>I checked with print-statements that the events used in enqueueNDRangeKernel calls are released with clReleaseEvent, which matches 1 to 1.

Maybe it's worth checking if no event ever get overwritten by another event, or if the internal pointer doesn't get corrupted by another bug? (That would cause leakage because clReleaseEvent would never see the original ptr).

Debugging whether there's a specific enqueueNDRangeKernel caller whose events are leaking might help.

>Normally you would check for nullptr or something, but the user's event might be a nullptr as well because it is an output argument, not an input argument.

You can have the user pass a pointer to his event. If it's a nullptr, you know he didn't pass an event, if it's a valid pointer, it can still point to a "nullptr" event. But there's no reason to get rid of internal events until you're totally desperate.

**Comment by CNugteren** [comment]
OK, I did some further digging. The internal events (category 1) were all handled already before. But now I found out that if I release the (potentially) user-passed event (category 2 or 3) just before the GEMM call returns, there are no more memory leaks (at least not on my system). If I release it just afterwards (like in the current `development` branch in the sample), it doesn't work.

Here is a 'patch' to remove the memory leaks from GEMM. I suppose I could do the same for other routines as well.
```
diff --git a/samples/sgemm.cpp b/samples/sgemm.cpp
index a4b8996..f55c1e1 100644
--- a/samples/sgemm.cpp
+++ b/samples/sgemm.cpp
@@ -80,6 +80,8 @@ int main() {
   queue.enqueueWriteBuffer(device_c, CL_TRUE, 0, host_c.size()*sizeof(float), host_c.data());
 
   // Start the timer
+  while(true)
+  {
   auto start_time = std::chrono::steady_clock::now();
 
   // Call the SGEMM routine. Note that the type of alpha and beta (float) determine the precision.
@@ -95,13 +97,12 @@ int main() {
                               &queue_plain, &event);
 
   // Record the execution time
-  clWaitForEvents(1, &event);
-  clReleaseEvent(event);
   auto elapsed_time = std::chrono::steady_clock::now() - start_time;
   auto time_ms = std::chrono::duration<double,std::milli>(elapsed_time).count();
 
   // Example completed. See "clblast.h" for status codes (0 -> success).
   printf("Completed SGEMM in %.3lf ms with status %d\n", time_ms, status);
+  }
   return 0;
 }
 
diff --git a/src/clblast.cpp b/src/clblast.cpp
index 79c30ca..16cd85b 100644
--- a/src/clblast.cpp
+++ b/src/clblast.cpp
@@ -1629,13 +1629,16 @@ StatusCode Gemm(const Layout layout, const Transpose a_transpose, const Transpos
   auto routine = Xgemm<T>(queue_cpp, event);
   auto status = routine.SetUp();
   if (status != StatusCode::kSuccess) { return status; }
-  return routine.DoGemm(layout, a_transpose, b_transpose,
+  status = routine.DoGemm(layout, a_transpose, b_transpose,
                         m, n, k,
                         alpha,
                         Buffer<T>(a_buffer), a_offset, a_ld,
                         Buffer<T>(b_buffer), b_offset, b_ld,
                         beta,
                         Buffer<T>(c_buffer), c_offset, c_ld);
+  queue_cpp.Finish();
+  clReleaseEvent(*event);
+  return status;
 }
 template StatusCode PUBLIC_API Gemm<float>(const Layout, const Transpose, const Transpose,
                                            const size_t, const size_t, const size_t,
```

Of course this is not a solution, because this way the user can't use the event any more. Any thoughts on why this is happening?

**Comment by gcp** [comment]
> Any thoughts on why this is happening?

Yes, it makes perfect sense now. Without the queue_cpp.Finish() in samples/sgemm.cpp, the sample code with the infinite loop will call enqueueNDRangeKernel a second time, before the first kernel has had the time to run or finish, yet pass the same &cl_event. Except that it's not a "nullptr" cl_event now, but one pointing to the event from the previous call. Now enqueueNDRangeKernel allocates a new event, overwrites event with the pointer to it, and boom, we've lost the reference to the original one.

Modifying the sample code by putting a for loop around that call doesn't work correctly if an &event is passed.

Now the real bug in CLBlast is that even if you'd pass a nullptr instead of event, it will leak memory.  This is case (3) above: https://github.com/CNugteren/CLBlast/issues/74#issuecomment-230104247

I'm looking at this now.

**Comment by gcp** [comment]
> before the first kernel has had the time to run or finish

Ah oops, that's what the clWaitForEvents(1, &event); is for, of course.

However, with a queue.finish() there it takes 5ms for an iteration. Without it, 0.1ms. That doesn't look right.

**Comment by gcp** [comment]
FYI http://stackoverflow.com/questions/27550574/opencl-clwaitevent-after-clfinish-cause-memory-leak

**Comment by gcp** [comment]
The fact that moving the same call one stack frame higher changes the result is rather indicative of a busted stack. I found some more places where CLBlast is careless with allocating enough memory to hold return values for OpenCL calls, but nothing that fixed the leak.

I did find that program.Build() was being called all the time, which makes no sense because all SGEMM calls are identical. Obviously, if the cache checks are failing, this means the kernel will be constantly recompiled and added to the cache, which will end up using a lot of memory...

After digging into ProgramCache.MatchInCache, the problem is that this code sees a different context every time.

Can you replicate this?

**Comment by CNugteren** [comment]
That bit is actually by design, see issue #47. It requires a re-build in case the context changed.

**Comment by gcp** [comment]
The sample code doesn't release the context though, so why would it change?

I saw the ProgramCache compare on ContextPointer, which is cl_context*.  Shouldn't it be comparing if the pointed-to context is identical instead, i.e. if cl_context == cl_context?

https://github.com/CNugteren/CLBlast/blob/7c13bacf129291e3e295ecb6e833788477085fa0/src/cache.hpp#L56

**Comment by CNugteren** [comment]
> I found some more places where CLBlast is careless with allocating enough memory to hold return values for OpenCL calls, but nothing that fixed the leak.

Could you let me know what those are, then I'll fix them. Thanks!

> I saw the ProgramCache compare on ContextPointer, which is cl_context*. Shouldn't it be comparing if the pointed-to context is identical instead, i.e. if cl_context == cl_context?

Yes, perhaps we should do that instead. But I am not sure if that's the way to do it, I'll have to investigate this further. The development version now has extra debug statements concerning storing/loading from the cache, for both the program and the binaries.

> The sample code doesn't release the context though, so why would it change?

It shouldn't indeed, but it does. Could that be the source of the memory leak? I am now explicitly clearing the `program_cache_` before storing a new entry and it seems that the memory consumption doesn't explode anymore. Or it just is a lot slower now and we don't see the effects?

I'll investigate further.

**Comment by CNugteren** [comment]
I believe I fixed the comparison of the contexts now in the latest version of `development`. This also seems to fix the memory leak issue (together with the earlier patch for the releasing of the events).

Could you also verify this on your machine? Thanks.

**Comment by gcp** [comment]
> Could you let me know what those are, then I'll fix them. Thanks!

See pull request #80 

I'll verify the leakage when I get back to my Windows machine.

**Comment by gcp** [comment]
Leaks confirmed fixed in development branch.
