### ISSUE TITLE
database.py default selection is suboptimal

### ISSUE THREAD

**Issue by gcp** [CNugteren/CLBlast#77]
https://github.com/CNugteren/CLBlast/commit/9683b50c557c7e415389b321d437be39ce0e519d#diff-f60ddfcd75f983a02970d3e99b6b81f4R89
https://github.com/CNugteren/CLBlast/commit/9683b50c557c7e415389b321d437be39ce0e519d#diff-f60ddfcd75f983a02970d3e99b6b81f4R260

If I read the source correctly, the default selection for a vendor currently takes the lowest value over all parameters in the best per-device kernels. This can generate defaults that are potentially bad on all devices, especially for "flag" parameters, or for sets of parameters that trade off against each other. It will get worse as more tuning is added.

I think you want to select the kernel that had the lowest average (or median) runtime over all devices, and didn't fail on any.

**Comment by CNugteren** [comment]
Indeed, the default parameters can be quite bad or might even result in incorrect values. As you observed correctly, it currently takes the lowest of the values for each particular device-type/vendor combination. The reason is that it's like this is that there is no right way to do it I guess.

Your suggestion seems a good approach: first filter out all parameter combinations that fail on one of the possible devices, and then get take the fastest one as a default. But still of course you cannot guarantee that it will work, but it will probably be better than the current default. One problem that I have with this is the following. For some kernels (only GEMM for now) there are too many parameters to explore, so a random subset is explored. This subset is of variable size and is not the same for each device. So, if we start filtering in that case, we will filter out a lot (if not all). Any suggestions there?

**Comment by gcp** [comment]
I would add a few hardcoded "baseline" configurations for every kernel, that are likely to widely work but explore some of the most significant parameters, manually constructed using your experience and the current database, and ensure those are always run during tuning. At worst, selecting the default will then boil down to selecting the baseline kernel that is the fastest on vendor X's devices.

**Comment by CNugteren** [comment]
Hmm, perhaps that could work. But that would require re-running some tuners on already tuned devices. I'll see how feasible that is. But for now I guess the first thing to do is implement this suggest for all other (non-GEMM) kernels. I'll let you know when that's done.

**Comment by gcp** [comment]
> manually constructed using your experience and the current database, and ensure those are always run during tuning

To avoid the manual guessing, perhaps a better procedure is to force the tuner to run all the kernels that are known to be optimal for some device (in other words, the exact parameter sets that are in the compiled-in database), before doing the random search.

**Comment by CNugteren** [comment]
I know it's been a while, but I finally merged in this idea. Right now the default entries in the database are computed as follows for each group (e.g. AMD GPU or Intel CPU):

1. Parameters combinations (i.e. configurations) which are not common across all devices of this group are discarded.

2. For the remaining parameter combinations: the sum of relative performances (between 0 and 1) across devices is computed. Note that this is relative because the sum of absolute execution times will be dominated by the slowest device.

3. The parameter combination with the highest sum of relative performances is chosen to be the default for this particular group.

This all works fine, except for GEMM as I remarked above. In that case no common parameter combination will be found, because tuners run a random subset of all combinations. For GEMM, the default parameters are still as before: the minimal values.

You made some suggestions above, but I am not too much in favour of them, because they require re-tuning and also don't fit well with the current tuning infrastructure. Do you have any other ideas that won't require re-tuning? I'll try to think of something as well. For now, at least for the other kernels default performance on un-seen devices should be a lot better.

**Comment by gcp** [comment]
If you have no common parameter set over all devices due to the GEMM tuner being probabilistic, I don't see how you'll get around to retuning (to some common set) to find optimal defaults.

But note that you could use the new defaults even if you don't receive new tuning for all devices. You'll just have a smaller "common results" set, that's still usable.

**Comment by CNugteren** [comment]
I have now changed the GEMM tuner to do two things:
* Try a fixed set of tuning parameters exhaustively
* Try a much larger set of tuning parameters by random sampling
That way there will be a common set of tuning parameters from which we can determine better defaults, as you suggested.

All that remains is to (re-)run the new GEMM tuners to populate the database with this common set of tuning parameters such that better defaults can be computed.

So I guess that closes this issue: default parameters of all non-GEMM kernels are improved, while the GEMM kernel's parameters will be improved in a while as soon as more/updated tuning results come in.
