### ISSUE TITLE
mesa cl

### ISSUE THREAD

**Issue by fommil** [CNugteren/CLBlast#87]
Hi, thanks for creating this project!

I'm the author of https://github.com/fommil/netlib-java and I'd really like to get this working for my Radeon R9 290x on ArchLinux.

I'm trying to do this using purely free/libre software, so I'm installing the mesa implementation of OpenCL. Have you ever looked into it or know if I'd need to do anything special?

**Comment by blueberry** [comment]
As far as I know, non-amd drivers do not support opencl at the sufficient level to be able to run this, let alone to run it with good performance.

**Comment by CNugteren** [comment]
I don't have access to a Linux machine with an AMD GPU, so I haven't tested Mesa. I am not sure about the status of their OpenCL support, there is some information on the internet, but not much. If it supports OpenCL, CLBlast should work. If the drivers are not that great, performance can still be OK I think, due to the auto-tuner eliminating funny cases w.r.t. compiler performance bugs. Slow compilation speed could be an issue, but if you repeatedly call BLAS functions it should be OK.

Let me know if you OpenCL is supported and whether you encounter any CLBlast specific issues.

**Comment by fommil** [comment]
FYI somebody on the mesa-dev mailing list has a patch to fix clblast to run against their implementation https://lists.freedesktop.org/archives/mesa-dev/2016-August/125153.html

**Comment by CNugteren** [comment]
I believe this is already fixed in the `development` branch:
```
    #ifdef CL_VERSION_2_0
      size_t ocl_version = device.VersionNumber();
      if (ocl_version >= 200)
      {
        cl_queue_properties properties[] = {CL_QUEUE_PROPERTIES, CL_QUEUE_PROFILING_ENABLE, 0};
        *queue_ = clCreateCommandQueueWithProperties(context(), device(), properties, &status);
      }
      else
      {
        *queue_ = clCreateCommandQueue(context(), device(), CL_QUEUE_PROFILING_ENABLE, &status);
      }
    #else
      *queue_ = clCreateCommandQueue(context(), device(), CL_QUEUE_PROFILING_ENABLE, &status);
    #endif
```

**Comment by bhack** [comment]
You can follow Nvidia status from https://phabricator.pmoreau.org/w/mesa/opencl_through_spirv_current_status/

**Comment by CNugteren** [comment]
@fommil Have you tested this based on the `development` branch?

**Comment by CNugteren** [comment]
I am closing this issue since I believe it was already fixed in `development` before it was reported. If you still encounter this issue, could you please re-open it?
