### ISSUE TITLE
dropin blas replacement?

### ISSUE THREAD

**Issue by hughperkins** [CNugteren/CLBlast#94]
it looks like nvblas can actually directly replace a standard non-gpu blas, ie install in place of openblas etc, and it will then automatically use the gpu to accelerate level 3 blas operations http://docs.nvidia.com/cuda/nvblas/index.html#axzz4IfVfPuKV

I dont think such a thing exists for opencl, but one could presumably make one relativley easily by combining openblas and CLblast, and using CLblast for anything that is n-cubey or so, ie level 3 operations, and openblas for everything else (which would otherwise be dominated by time spent copygin to gpu and back).  Thoughts on:
- if such a thing alrady exists? (not necessarily using CLblast, eg viennacl? clblas? etc)
- usefulness of such a thing?
- interest in writing it? (I'm pondeirng writing it, seems like just a few wrapper methods I guess?)

**Comment by CNugteren** [comment]
* I don't think clBLAS has it, I am not sure about ViennaCL. Apple's Accelerate framework definitely has it, but that's closed source.
* That makes sense to do, yes. I already played with this idea for a bit.
* Since some files in CLBlast are generated from Python, it is not too much work to make a CBLAS interface to them. Actually deciding whether or not to use the OpenCL version is perhaps up to someone else - or do you think that should be within CLBlast? I don't want to make CLBlast dependent on for example OpenBLAS, so perhaps that's something for an external project?

**Comment by blueberry** [comment]
I am not sure whether I understand you well that you are talking about  replacing CPU BLAS implementation "transparently". Please at least allow the option to disable that. In my use cases, I need to control (and know) which implementation gets called. So, If I call CPU BLAS, I need to be sure CPU BLAS is called, even when/if it is slower. If I want GPU, I prefer to call it myself.

**Comment by CNugteren** [comment]
Of course, everything that we talk about is on top of the existing CLBlast functionality. So it would be a separate header that users can make calls to (or not). It will be a header with the same interface as the Netlib BLAS standard (`cblas.h`). At least, this is how I understand @hughperkins's request.

So technically this would mean that such a function call will result in creating a (default?) OpenCL platform, device, context, and queue, followed by a buffer write, a call to the regular CLBlast, and a final buffer read to get the results back. This will not be useful for most people, as it requires a lot of overhead. However, it's easy to use for people already calling Netlib BLAS functions. And it will indeed benefit mostly level-3 functions, as copying overhead is n^2 and the computation is n^3.

**Comment by CNugteren** [comment]
There is a first version of this API now available in the `netlib_blas_api` branch. It is not 100% finished, some functions don't have the exact same signature as in CBLAS. Also, it hasn't been tested properly, just with one example (included as `samples/sgemm_netlib.c`). From the README:

There is also a Netlib CBLAS C API available. This is however not recommended for full control over performance, since at every call it will copy all buffers to and from the OpenCL device. Especially for level 1 and level 2 BLAS functions performance will be impacted severly. However, it can be useful if you don't want to touch OpenCL at all. You can set the default device and platform by setting the `CLBLAST_DEVICE` and `CLBLAST_PLATFORM` environmental variables. This API can be used as follows:

    #include <clblast_netlib_c.h>

Is this what you had in mind? Or do you have any suggestions?

**Comment by CNugteren** [comment]
This is now finished and merged into the `development` branch. It will be in the next release.

The API is fully Netlib CBLAS compatible. From the README:

> There is also a Netlib CBLAS C API available. This is however not recommended for full control over performance, since at every call it will copy all buffers to and from the OpenCL device. Especially for level 1 and level 2 BLAS functions performance will be impacted severely. However, it can be useful if you don't want to touch OpenCL at all. You can set the default device and platform by setting the `CLBLAST_DEVICE` and `CLBLAST_PLATFORM` environmental variables. This API can be used as follows after providing the `-DNETLIB=ON` flag to CMake: `#include <clblast_netlib_c.h>`

**Comment by hughperkins** [comment]
Awesome, thanks! :-)

**Comment by tholu** [comment]
Is it possible to use it as a drop-in replacement for octave similar to NVBLAS as described [here](https://devblogs.nvidia.com/drop-in-acceleration-gnu-octave/)? My first probably naive attempt did not work (or no GPUs got recognized, any way to test this?). 

`LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libclblast.so octave benchmark.m`

**Comment by tholu** [comment]
I tried this:

```
$ ls -la /usr/local/lib/libblas
total 8
drwxr-xr-x 2 root root 4096 Oct 19 18:48 .
drwxr-xr-x 5 root root 4096 Oct 19 18:46 ..
lrwxrwxrwx 1 root root   39 Oct 19 18:46 libblas.so.3 -> /usr/lib/x86_64-linux-gnu/libclblast.so
lrwxrwxrwx 1 root root   39 Oct 19 18:48 libopenblas.so.0 -> /usr/lib/x86_64-linux-gnu/libclblast.so

$ ldd /usr/lib/x86_64-linux-gnu/liboctave.so.3 | grep blas
	libblas.so.3 => /usr/local/lib/libblas/libblas.so.3 (0x00007faf46f37000)

$ octave benchmark.m
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
/usr/bin/octave-cli: symbol lookup error: /usr/lib/liblapack.so.3: undefined symbol: sgetrs_N_parallel
```

It seems dropin is currently not possible. Or am I doing it wrong?

**Comment by CNugteren** [comment]
Could you open a separate issue for this? But I'm also not sure I can help you out there, the error message is related to LAPACK, not BLAS. The function `sgetrs` is also not part of BLAS but of LAPACK, so you seem to be doing something else wrong there.
